// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type AuthorizePaymentRequest struct {
	// An object that contains the decrypted card details.
	DecryptedCardDetails *AuthorizePaymentRequestDecryptedCardDetails `json:"decrypted_card_details,omitempty" url:"-"`
}

// Response from the Authorize Payment API (Apple Pay).
type AuthorizePaymentResponse struct {
	Data *AuthorizePaymentResponseData `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponse) GetData() *AuthorizePaymentResponseData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AuthorizePaymentResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponse) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseData struct {
	OrderID                *string                                  `json:"order_id,omitempty" url:"order_id,omitempty"`
	MerchantOrderReference *string                                  `json:"merchant_order_reference,omitempty" url:"merchant_order_reference,omitempty"`
	Type                   *AuthorizePaymentResponseDataType        `json:"type,omitempty" url:"type,omitempty"`
	Status                 *AuthorizePaymentResponseDataStatus      `json:"status,omitempty" url:"status,omitempty"`
	CallbackURL            *string                                  `json:"callback_url,omitempty" url:"callback_url,omitempty"`
	FailureCallbackURL     *string                                  `json:"failure_callback_url,omitempty" url:"failure_callback_url,omitempty"`
	MerchantID             *string                                  `json:"merchant_id,omitempty" url:"merchant_id,omitempty"`
	OrderAmount            *AuthorizePaymentResponseDataOrderAmount `json:"order_amount,omitempty" url:"order_amount,omitempty"`
	PreAuth                *bool                                    `json:"pre_auth,omitempty" url:"pre_auth,omitempty"`
	// Whether the transaction is a part payment.
	PartPayment           *bool                                        `json:"part_payment,omitempty" url:"part_payment,omitempty"`
	AllowedPaymentMethods []string                                     `json:"allowed_payment_methods,omitempty" url:"allowed_payment_methods,omitempty"`
	PurchaseDetails       *AuthorizePaymentResponseDataPurchaseDetails `json:"purchase_details,omitempty" url:"purchase_details,omitempty"`
	Payments              []*AuthorizePaymentResponseDataPaymentsItem  `json:"payments,omitempty" url:"payments,omitempty"`
	CreatedAt             *time.Time                                   `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt             *time.Time                                   `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	IntegrationMode       *AuthorizePaymentResponseDataIntegrationMode `json:"integration_mode,omitempty" url:"integration_mode,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseData) GetOrderID() *string {
	if a == nil {
		return nil
	}
	return a.OrderID
}

func (a *AuthorizePaymentResponseData) GetMerchantOrderReference() *string {
	if a == nil {
		return nil
	}
	return a.MerchantOrderReference
}

func (a *AuthorizePaymentResponseData) GetType() *AuthorizePaymentResponseDataType {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AuthorizePaymentResponseData) GetStatus() *AuthorizePaymentResponseDataStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AuthorizePaymentResponseData) GetCallbackURL() *string {
	if a == nil {
		return nil
	}
	return a.CallbackURL
}

func (a *AuthorizePaymentResponseData) GetFailureCallbackURL() *string {
	if a == nil {
		return nil
	}
	return a.FailureCallbackURL
}

func (a *AuthorizePaymentResponseData) GetMerchantID() *string {
	if a == nil {
		return nil
	}
	return a.MerchantID
}

func (a *AuthorizePaymentResponseData) GetOrderAmount() *AuthorizePaymentResponseDataOrderAmount {
	if a == nil {
		return nil
	}
	return a.OrderAmount
}

func (a *AuthorizePaymentResponseData) GetPreAuth() *bool {
	if a == nil {
		return nil
	}
	return a.PreAuth
}

func (a *AuthorizePaymentResponseData) GetPartPayment() *bool {
	if a == nil {
		return nil
	}
	return a.PartPayment
}

func (a *AuthorizePaymentResponseData) GetAllowedPaymentMethods() []string {
	if a == nil {
		return nil
	}
	return a.AllowedPaymentMethods
}

func (a *AuthorizePaymentResponseData) GetPurchaseDetails() *AuthorizePaymentResponseDataPurchaseDetails {
	if a == nil {
		return nil
	}
	return a.PurchaseDetails
}

func (a *AuthorizePaymentResponseData) GetPayments() []*AuthorizePaymentResponseDataPaymentsItem {
	if a == nil {
		return nil
	}
	return a.Payments
}

func (a *AuthorizePaymentResponseData) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AuthorizePaymentResponseData) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AuthorizePaymentResponseData) GetIntegrationMode() *AuthorizePaymentResponseDataIntegrationMode {
	if a == nil {
		return nil
	}
	return a.IntegrationMode
}

func (a *AuthorizePaymentResponseData) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseData) UnmarshalJSON(data []byte) error {
	type embed AuthorizePaymentResponseData
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseData(unmarshaler.embed)
	a.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	a.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseData) MarshalJSON() ([]byte, error) {
	type embed AuthorizePaymentResponseData
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*a),
		CreatedAt: core.NewOptionalDateTime(a.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(a.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (a *AuthorizePaymentResponseData) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataIntegrationMode string

const (
	AuthorizePaymentResponseDataIntegrationModeSeamless AuthorizePaymentResponseDataIntegrationMode = "SEAMLESS"
	AuthorizePaymentResponseDataIntegrationModeRedirect AuthorizePaymentResponseDataIntegrationMode = "REDIRECT"
)

func NewAuthorizePaymentResponseDataIntegrationModeFromString(s string) (AuthorizePaymentResponseDataIntegrationMode, error) {
	switch s {
	case "SEAMLESS":
		return AuthorizePaymentResponseDataIntegrationModeSeamless, nil
	case "REDIRECT":
		return AuthorizePaymentResponseDataIntegrationModeRedirect, nil
	}
	var t AuthorizePaymentResponseDataIntegrationMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataIntegrationMode) Ptr() *AuthorizePaymentResponseDataIntegrationMode {
	return &a
}

type AuthorizePaymentResponseDataOrderAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataOrderAmount) GetValue() *int {
	if a == nil {
		return nil
	}
	return a.Value
}

func (a *AuthorizePaymentResponseDataOrderAmount) GetCurrency() *string {
	if a == nil {
		return nil
	}
	return a.Currency
}

func (a *AuthorizePaymentResponseDataOrderAmount) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataOrderAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataOrderAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataOrderAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataOrderAmount) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItem struct {
	ID                       *string                                                `json:"id,omitempty" url:"id,omitempty"`
	MerchantPaymentReference *string                                                `json:"merchant_payment_reference,omitempty" url:"merchant_payment_reference,omitempty"`
	Status                   *AuthorizePaymentResponseDataPaymentsItemStatus        `json:"status,omitempty" url:"status,omitempty"`
	PaymentAmount            *AuthorizePaymentResponseDataPaymentsItemPaymentAmount `json:"payment_amount,omitempty" url:"payment_amount,omitempty"`
	PaymentMethod            *AuthorizePaymentResponseDataPaymentsItemPaymentMethod `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	PaymentOption            *AuthorizePaymentResponseDataPaymentsItemPaymentOption `json:"payment_option,omitempty" url:"payment_option,omitempty"`
	AcquirerData             *AuthorizePaymentResponseDataPaymentsItemAcquirerData  `json:"acquirer_data,omitempty" url:"acquirer_data,omitempty"`
	CreatedAt                *time.Time                                             `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt                *time.Time                                             `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetMerchantPaymentReference() *string {
	if a == nil {
		return nil
	}
	return a.MerchantPaymentReference
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetStatus() *AuthorizePaymentResponseDataPaymentsItemStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetPaymentAmount() *AuthorizePaymentResponseDataPaymentsItemPaymentAmount {
	if a == nil {
		return nil
	}
	return a.PaymentAmount
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetPaymentMethod() *AuthorizePaymentResponseDataPaymentsItemPaymentMethod {
	if a == nil {
		return nil
	}
	return a.PaymentMethod
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetPaymentOption() *AuthorizePaymentResponseDataPaymentsItemPaymentOption {
	if a == nil {
		return nil
	}
	return a.PaymentOption
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetAcquirerData() *AuthorizePaymentResponseDataPaymentsItemAcquirerData {
	if a == nil {
		return nil
	}
	return a.AcquirerData
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AuthorizePaymentResponseDataPaymentsItem) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPaymentsItem) UnmarshalJSON(data []byte) error {
	type embed AuthorizePaymentResponseDataPaymentsItem
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPaymentsItem(unmarshaler.embed)
	a.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	a.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPaymentsItem) MarshalJSON() ([]byte, error) {
	type embed AuthorizePaymentResponseDataPaymentsItem
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*a),
		CreatedAt: core.NewOptionalDateTime(a.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(a.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (a *AuthorizePaymentResponseDataPaymentsItem) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItemAcquirerData struct {
	ApprovalCode      *string `json:"approval_code,omitempty" url:"approval_code,omitempty"`
	AcquirerReference *string `json:"acquirer_reference,omitempty" url:"acquirer_reference,omitempty"`
	Rrn               *string `json:"rrn,omitempty" url:"rrn,omitempty"`
	IsAggregator      *bool   `json:"is_aggregator,omitempty" url:"is_aggregator,omitempty"`
	AcquirerName      *string `json:"acquirer_name,omitempty" url:"acquirer_name,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) GetApprovalCode() *string {
	if a == nil {
		return nil
	}
	return a.ApprovalCode
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) GetAcquirerReference() *string {
	if a == nil {
		return nil
	}
	return a.AcquirerReference
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) GetRrn() *string {
	if a == nil {
		return nil
	}
	return a.Rrn
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) GetIsAggregator() *bool {
	if a == nil {
		return nil
	}
	return a.IsAggregator
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) GetAcquirerName() *string {
	if a == nil {
		return nil
	}
	return a.AcquirerName
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPaymentsItemAcquirerData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPaymentsItemAcquirerData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPaymentsItemAcquirerData) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItemPaymentAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentAmount) GetValue() *int {
	if a == nil {
		return nil
	}
	return a.Value
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentAmount) GetCurrency() *string {
	if a == nil {
		return nil
	}
	return a.Currency
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentAmount) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPaymentsItemPaymentAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPaymentsItemPaymentAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentAmount) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItemPaymentMethod string

const (
	AuthorizePaymentResponseDataPaymentsItemPaymentMethodCard       AuthorizePaymentResponseDataPaymentsItemPaymentMethod = "CARD"
	AuthorizePaymentResponseDataPaymentsItemPaymentMethodUpi        AuthorizePaymentResponseDataPaymentsItemPaymentMethod = "UPI"
	AuthorizePaymentResponseDataPaymentsItemPaymentMethodPoints     AuthorizePaymentResponseDataPaymentsItemPaymentMethod = "POINTS"
	AuthorizePaymentResponseDataPaymentsItemPaymentMethodNetbanking AuthorizePaymentResponseDataPaymentsItemPaymentMethod = "NETBANKING"
	AuthorizePaymentResponseDataPaymentsItemPaymentMethodWallet     AuthorizePaymentResponseDataPaymentsItemPaymentMethod = "WALLET"
)

func NewAuthorizePaymentResponseDataPaymentsItemPaymentMethodFromString(s string) (AuthorizePaymentResponseDataPaymentsItemPaymentMethod, error) {
	switch s {
	case "CARD":
		return AuthorizePaymentResponseDataPaymentsItemPaymentMethodCard, nil
	case "UPI":
		return AuthorizePaymentResponseDataPaymentsItemPaymentMethodUpi, nil
	case "POINTS":
		return AuthorizePaymentResponseDataPaymentsItemPaymentMethodPoints, nil
	case "NETBANKING":
		return AuthorizePaymentResponseDataPaymentsItemPaymentMethodNetbanking, nil
	case "WALLET":
		return AuthorizePaymentResponseDataPaymentsItemPaymentMethodWallet, nil
	}
	var t AuthorizePaymentResponseDataPaymentsItemPaymentMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataPaymentsItemPaymentMethod) Ptr() *AuthorizePaymentResponseDataPaymentsItemPaymentMethod {
	return &a
}

type AuthorizePaymentResponseDataPaymentsItemPaymentOption struct {
	WalletData *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData `json:"wallet_data,omitempty" url:"wallet_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOption) GetWalletData() *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData {
	if a == nil {
		return nil
	}
	return a.WalletData
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOption) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOption) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPaymentsItemPaymentOption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPaymentsItemPaymentOption(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOption) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData struct {
	WalletCode     *string                                                                        `json:"wallet_code,omitempty" url:"wallet_code,omitempty"`
	WalletCardData *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData `json:"wallet_card_data,omitempty" url:"wallet_card_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData) GetWalletCode() *string {
	if a == nil {
		return nil
	}
	return a.WalletCode
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData) GetWalletCardData() *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData {
	if a == nil {
		return nil
	}
	return a.WalletCardData
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletData) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData struct {
	CardType       *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType     `json:"card_type,omitempty" url:"card_type,omitempty"`
	NetworkName    *string                                                                                    `json:"network_name,omitempty" url:"network_name,omitempty"`
	IssuerName     *string                                                                                    `json:"issuer_name,omitempty" url:"issuer_name,omitempty"`
	CardCategory   *string                                                                                    `json:"card_category,omitempty" url:"card_category,omitempty"`
	CountryCode    *string                                                                                    `json:"country_code,omitempty" url:"country_code,omitempty"`
	TokenTxnType   *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType `json:"token_txn_type,omitempty" url:"token_txn_type,omitempty"`
	Save           *bool                                                                                      `json:"save,omitempty" url:"save,omitempty"`
	CardHolderName *string                                                                                    `json:"card_holder_name,omitempty" url:"card_holder_name,omitempty"`
	BinMin         *string                                                                                    `json:"bin_min,omitempty" url:"bin_min,omitempty"`
	BinMax         *string                                                                                    `json:"bin_max,omitempty" url:"bin_max,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetCardType() *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType {
	if a == nil {
		return nil
	}
	return a.CardType
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetNetworkName() *string {
	if a == nil {
		return nil
	}
	return a.NetworkName
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetIssuerName() *string {
	if a == nil {
		return nil
	}
	return a.IssuerName
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetCardCategory() *string {
	if a == nil {
		return nil
	}
	return a.CardCategory
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetCountryCode() *string {
	if a == nil {
		return nil
	}
	return a.CountryCode
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetTokenTxnType() *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType {
	if a == nil {
		return nil
	}
	return a.TokenTxnType
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetSave() *bool {
	if a == nil {
		return nil
	}
	return a.Save
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetCardHolderName() *string {
	if a == nil {
		return nil
	}
	return a.CardHolderName
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetBinMin() *string {
	if a == nil {
		return nil
	}
	return a.BinMin
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetBinMax() *string {
	if a == nil {
		return nil
	}
	return a.BinMax
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardData) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType string

const (
	AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardTypeDebit  AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType = "DEBIT"
	AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardTypeCredit AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType = "CREDIT"
)

func NewAuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardTypeFromString(s string) (AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType, error) {
	switch s {
	case "DEBIT":
		return AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardTypeDebit, nil
	case "CREDIT":
		return AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardTypeCredit, nil
	}
	var t AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType) Ptr() *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataCardType {
	return &a
}

type AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType string

const (
	AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeAltToken     AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType = "ALT_TOKEN"
	AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeNetworkToken AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType = "NETWORK_TOKEN"
	AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeIssuerToken  AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType = "ISSUER_TOKEN"
)

func NewAuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeFromString(s string) (AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType, error) {
	switch s {
	case "ALT_TOKEN":
		return AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeAltToken, nil
	case "NETWORK_TOKEN":
		return AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeNetworkToken, nil
	case "ISSUER_TOKEN":
		return AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnTypeIssuerToken, nil
	}
	var t AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType) Ptr() *AuthorizePaymentResponseDataPaymentsItemPaymentOptionWalletDataWalletCardDataTokenTxnType {
	return &a
}

type AuthorizePaymentResponseDataPaymentsItemStatus string

const (
	AuthorizePaymentResponseDataPaymentsItemStatusPending    AuthorizePaymentResponseDataPaymentsItemStatus = "PENDING"
	AuthorizePaymentResponseDataPaymentsItemStatusAuthorized AuthorizePaymentResponseDataPaymentsItemStatus = "AUTHORIZED"
	AuthorizePaymentResponseDataPaymentsItemStatusCancelled  AuthorizePaymentResponseDataPaymentsItemStatus = "CANCELLED"
	AuthorizePaymentResponseDataPaymentsItemStatusProcessed  AuthorizePaymentResponseDataPaymentsItemStatus = "PROCESSED"
	AuthorizePaymentResponseDataPaymentsItemStatusFailed     AuthorizePaymentResponseDataPaymentsItemStatus = "FAILED"
)

func NewAuthorizePaymentResponseDataPaymentsItemStatusFromString(s string) (AuthorizePaymentResponseDataPaymentsItemStatus, error) {
	switch s {
	case "PENDING":
		return AuthorizePaymentResponseDataPaymentsItemStatusPending, nil
	case "AUTHORIZED":
		return AuthorizePaymentResponseDataPaymentsItemStatusAuthorized, nil
	case "CANCELLED":
		return AuthorizePaymentResponseDataPaymentsItemStatusCancelled, nil
	case "PROCESSED":
		return AuthorizePaymentResponseDataPaymentsItemStatusProcessed, nil
	case "FAILED":
		return AuthorizePaymentResponseDataPaymentsItemStatusFailed, nil
	}
	var t AuthorizePaymentResponseDataPaymentsItemStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataPaymentsItemStatus) Ptr() *AuthorizePaymentResponseDataPaymentsItemStatus {
	return &a
}

type AuthorizePaymentResponseDataPurchaseDetails struct {
	Customer         *AuthorizePaymentResponseDataPurchaseDetailsCustomer `json:"customer,omitempty" url:"customer,omitempty"`
	MerchantMetadata *MerchantMetadata                                    `json:"merchant_metadata,omitempty" url:"merchant_metadata,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPurchaseDetails) GetCustomer() *AuthorizePaymentResponseDataPurchaseDetailsCustomer {
	if a == nil {
		return nil
	}
	return a.Customer
}

func (a *AuthorizePaymentResponseDataPurchaseDetails) GetMerchantMetadata() *MerchantMetadata {
	if a == nil {
		return nil
	}
	return a.MerchantMetadata
}

func (a *AuthorizePaymentResponseDataPurchaseDetails) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPurchaseDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPurchaseDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPurchaseDetails(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPurchaseDetails) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataPurchaseDetailsCustomer struct {
	EmailID                      *string  `json:"email_id,omitempty" url:"email_id,omitempty"`
	FirstName                    *string  `json:"first_name,omitempty" url:"first_name,omitempty"`
	LastName                     *string  `json:"last_name,omitempty" url:"last_name,omitempty"`
	MobileNumber                 *string  `json:"mobile_number,omitempty" url:"mobile_number,omitempty"`
	CountryCode                  *string  `json:"country_code,omitempty" url:"country_code,omitempty"`
	BillingAddress               *Address `json:"billing_address,omitempty" url:"billing_address,omitempty"`
	ShippingAddress              *Address `json:"shipping_address,omitempty" url:"shipping_address,omitempty"`
	IsEditCustomerDetailsAllowed *bool    `json:"is_edit_customer_details_allowed,omitempty" url:"is_edit_customer_details_allowed,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetEmailID() *string {
	if a == nil {
		return nil
	}
	return a.EmailID
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetFirstName() *string {
	if a == nil {
		return nil
	}
	return a.FirstName
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetLastName() *string {
	if a == nil {
		return nil
	}
	return a.LastName
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetMobileNumber() *string {
	if a == nil {
		return nil
	}
	return a.MobileNumber
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetCountryCode() *string {
	if a == nil {
		return nil
	}
	return a.CountryCode
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetBillingAddress() *Address {
	if a == nil {
		return nil
	}
	return a.BillingAddress
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetShippingAddress() *Address {
	if a == nil {
		return nil
	}
	return a.ShippingAddress
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetIsEditCustomerDetailsAllowed() *bool {
	if a == nil {
		return nil
	}
	return a.IsEditCustomerDetailsAllowed
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentResponseDataPurchaseDetailsCustomer
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentResponseDataPurchaseDetailsCustomer(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentResponseDataPurchaseDetailsCustomer) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuthorizePaymentResponseDataStatus string

const (
	AuthorizePaymentResponseDataStatusCreated           AuthorizePaymentResponseDataStatus = "CREATED"
	AuthorizePaymentResponseDataStatusPending           AuthorizePaymentResponseDataStatus = "PENDING"
	AuthorizePaymentResponseDataStatusProcessed         AuthorizePaymentResponseDataStatus = "PROCESSED"
	AuthorizePaymentResponseDataStatusAuthorized        AuthorizePaymentResponseDataStatus = "AUTHORIZED"
	AuthorizePaymentResponseDataStatusCancelled         AuthorizePaymentResponseDataStatus = "CANCELLED"
	AuthorizePaymentResponseDataStatusAttempted         AuthorizePaymentResponseDataStatus = "ATTEMPTED"
	AuthorizePaymentResponseDataStatusFailed            AuthorizePaymentResponseDataStatus = "FAILED"
	AuthorizePaymentResponseDataStatusFullyRefunded     AuthorizePaymentResponseDataStatus = "FULLY_REFUNDED"
	AuthorizePaymentResponseDataStatusPartiallyRefunded AuthorizePaymentResponseDataStatus = "PARTIALLY_REFUNDED"
)

func NewAuthorizePaymentResponseDataStatusFromString(s string) (AuthorizePaymentResponseDataStatus, error) {
	switch s {
	case "CREATED":
		return AuthorizePaymentResponseDataStatusCreated, nil
	case "PENDING":
		return AuthorizePaymentResponseDataStatusPending, nil
	case "PROCESSED":
		return AuthorizePaymentResponseDataStatusProcessed, nil
	case "AUTHORIZED":
		return AuthorizePaymentResponseDataStatusAuthorized, nil
	case "CANCELLED":
		return AuthorizePaymentResponseDataStatusCancelled, nil
	case "ATTEMPTED":
		return AuthorizePaymentResponseDataStatusAttempted, nil
	case "FAILED":
		return AuthorizePaymentResponseDataStatusFailed, nil
	case "FULLY_REFUNDED":
		return AuthorizePaymentResponseDataStatusFullyRefunded, nil
	case "PARTIALLY_REFUNDED":
		return AuthorizePaymentResponseDataStatusPartiallyRefunded, nil
	}
	var t AuthorizePaymentResponseDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataStatus) Ptr() *AuthorizePaymentResponseDataStatus {
	return &a
}

type AuthorizePaymentResponseDataType string

const (
	AuthorizePaymentResponseDataTypeCharge AuthorizePaymentResponseDataType = "CHARGE"
	AuthorizePaymentResponseDataTypeRefund AuthorizePaymentResponseDataType = "REFUND"
)

func NewAuthorizePaymentResponseDataTypeFromString(s string) (AuthorizePaymentResponseDataType, error) {
	switch s {
	case "CHARGE":
		return AuthorizePaymentResponseDataTypeCharge, nil
	case "REFUND":
		return AuthorizePaymentResponseDataTypeRefund, nil
	}
	var t AuthorizePaymentResponseDataType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentResponseDataType) Ptr() *AuthorizePaymentResponseDataType {
	return &a
}

// An object that contains the decrypted card details.
type AuthorizePaymentRequestDecryptedCardDetails struct {
	// Unique identifier of the card as per the token transaction type.
	// Supported characters: A-Z, a-z, 0-9, . / \\ - _ , ( ) '
	Token string `json:"token" url:"token"`
	// Card token expiry month. Must be 2 digits.
	ExpirationMonth string `json:"expiration_month" url:"expiration_month"`
	// Card token expiry year. Must be 4 digits.
	ExpirationYear string `json:"expiration_year" url:"expiration_year"`
	// Unique encrypted text from the Apple Pay token.
	Cryptogram string `json:"cryptogram" url:"cryptogram"`
	// Unique encrypted text. **Mandatory for Mastercard.**
	Cavv *string `json:"cavv,omitempty" url:"cavv,omitempty"`
	// Indicates the authentication outcome for the transaction.
	Eci *string `json:"eci,omitempty" url:"eci,omitempty"`
	// An object that contains additional card meta details.
	CardMetaData *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData `json:"card_meta_data,omitempty" url:"card_meta_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetToken() string {
	if a == nil {
		return ""
	}
	return a.Token
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetExpirationMonth() string {
	if a == nil {
		return ""
	}
	return a.ExpirationMonth
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetExpirationYear() string {
	if a == nil {
		return ""
	}
	return a.ExpirationYear
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetCryptogram() string {
	if a == nil {
		return ""
	}
	return a.Cryptogram
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetCavv() *string {
	if a == nil {
		return nil
	}
	return a.Cavv
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetEci() *string {
	if a == nil {
		return nil
	}
	return a.Eci
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetCardMetaData() *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData {
	if a == nil {
		return nil
	}
	return a.CardMetaData
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentRequestDecryptedCardDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentRequestDecryptedCardDetails(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentRequestDecryptedCardDetails) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// An object that contains additional card meta details.
type AuthorizePaymentRequestDecryptedCardDetailsCardMetaData struct {
	// Type of the card.
	CardType AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType `json:"card_type" url:"card_type"`
	// Type of card network.
	NetworkName AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName `json:"network_name" url:"network_name"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData) GetCardType() AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType {
	if a == nil {
		return ""
	}
	return a.CardType
}

func (a *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData) GetNetworkName() AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName {
	if a == nil {
		return ""
	}
	return a.NetworkName
}

func (a *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorizePaymentRequestDecryptedCardDetailsCardMetaData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthorizePaymentRequestDecryptedCardDetailsCardMetaData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthorizePaymentRequestDecryptedCardDetailsCardMetaData) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Type of the card.
type AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType string

const (
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypeCredit  AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType = "CREDIT"
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypeDebit   AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType = "DEBIT"
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypePrepaid AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType = "PREPAID"
)

func NewAuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypeFromString(s string) (AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType, error) {
	switch s {
	case "CREDIT":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypeCredit, nil
	case "DEBIT":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypeDebit, nil
	case "PREPAID":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardTypePrepaid, nil
	}
	var t AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType) Ptr() *AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataCardType {
	return &a
}

// Type of card network.
type AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName string

const (
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameVisa       AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName = "VISA"
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameMastercard AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName = "MASTERCARD"
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameRupay      AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName = "RUPAY"
	AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameAmex       AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName = "AMEX"
)

func NewAuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameFromString(s string) (AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName, error) {
	switch s {
	case "VISA":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameVisa, nil
	case "MASTERCARD":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameMastercard, nil
	case "RUPAY":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameRupay, nil
	case "AMEX":
		return AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkNameAmex, nil
	}
	var t AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName) Ptr() *AuthorizePaymentRequestDecryptedCardDetailsCardMetaDataNetworkName {
	return &a
}
