// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type GenerateTokenRequest struct {
	// Unique client identifier provided during merchant onboarding.
	ClientID string `json:"client_id" url:"-"`
	// Client secret key provided during merchant onboarding.
	ClientSecret string `json:"client_secret" url:"-"`
	// OAuth2 grant type.
	GrantType string `json:"grant_type" url:"-"`
}

// Response containing the generated access token.
type GenerateTokenResponse struct {
	// The access token generated by the system. Use in Authorization headers.
	AccessToken *string `json:"access_token,omitempty" url:"access_token,omitempty"`
	// Access token expiration timestamp in ISO 8601 format.
	ExpiresAt *time.Time `json:"expires_at,omitempty" url:"expires_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GenerateTokenResponse) GetAccessToken() *string {
	if g == nil {
		return nil
	}
	return g.AccessToken
}

func (g *GenerateTokenResponse) GetExpiresAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ExpiresAt
}

func (g *GenerateTokenResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GenerateTokenResponse) UnmarshalJSON(data []byte) error {
	type embed GenerateTokenResponse
	var unmarshaler = struct {
		embed
		ExpiresAt *core.DateTime `json:"expires_at,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GenerateTokenResponse(unmarshaler.embed)
	g.ExpiresAt = unmarshaler.ExpiresAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GenerateTokenResponse) MarshalJSON() ([]byte, error) {
	type embed GenerateTokenResponse
	var marshaler = struct {
		embed
		ExpiresAt *core.DateTime `json:"expires_at,omitempty"`
	}{
		embed:     embed(*g),
		ExpiresAt: core.NewOptionalDateTime(g.ExpiresAt),
	}
	return json.Marshal(marshaler)
}

func (g *GenerateTokenResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
