// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CalculateConvenienceFeeRequest struct {
	Amount *Amount `json:"amount,omitempty" url:"-"`
	// Payment method for fee calculation.
	PaymentMethod string `json:"payment_method" url:"-"`
	// Card network type for more specific fee calculation.
	NetworkType *string `json:"network_type,omitempty" url:"-"`
}

// Response containing convenience fee breakdown.
type CalculateConvenienceFeeResponse struct {
	// Array of convenience fee results per payment method/network combination.
	Data []*CalculateConvenienceFeeResponseDataItem `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CalculateConvenienceFeeResponse) GetData() []*CalculateConvenienceFeeResponseDataItem {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CalculateConvenienceFeeResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CalculateConvenienceFeeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CalculateConvenienceFeeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CalculateConvenienceFeeResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CalculateConvenienceFeeResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CalculateConvenienceFeeResponseDataItem struct {
	// Payment method.
	PaymentMethod *string `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	// Type of fee calculation.
	FeeType *string `json:"fee_type,omitempty" url:"fee_type,omitempty"`
	Amount  *Amount `json:"amount,omitempty" url:"amount,omitempty"`
	// Breakdown of the convenience fee.
	ConvenienceFeeBreakdown *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown `json:"convenience_fee_breakdown,omitempty" url:"convenience_fee_breakdown,omitempty"`
	PayableAmount           *Amount                                                         `json:"payable_amount,omitempty" url:"payable_amount,omitempty"`
	// Metadata about the payment method.
	PaymentMethodMetadata *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata `json:"payment_method_metadata,omitempty" url:"payment_method_metadata,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CalculateConvenienceFeeResponseDataItem) GetPaymentMethod() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethod
}

func (c *CalculateConvenienceFeeResponseDataItem) GetFeeType() *string {
	if c == nil {
		return nil
	}
	return c.FeeType
}

func (c *CalculateConvenienceFeeResponseDataItem) GetAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CalculateConvenienceFeeResponseDataItem) GetConvenienceFeeBreakdown() *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown {
	if c == nil {
		return nil
	}
	return c.ConvenienceFeeBreakdown
}

func (c *CalculateConvenienceFeeResponseDataItem) GetPayableAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.PayableAmount
}

func (c *CalculateConvenienceFeeResponseDataItem) GetPaymentMethodMetadata() *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata {
	if c == nil {
		return nil
	}
	return c.PaymentMethodMetadata
}

func (c *CalculateConvenienceFeeResponseDataItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CalculateConvenienceFeeResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CalculateConvenienceFeeResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CalculateConvenienceFeeResponseDataItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CalculateConvenienceFeeResponseDataItem) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Breakdown of the convenience fee.
type CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown struct {
	FeeAmount           *Amount `json:"fee_amount,omitempty" url:"fee_amount,omitempty"`
	TaxAmount           *Amount `json:"tax_amount,omitempty" url:"tax_amount,omitempty"`
	AdditionalFeeAmount *Amount `json:"additional_fee_amount,omitempty" url:"additional_fee_amount,omitempty"`
	MaximumFeeAmount    *Amount `json:"maximum_fee_amount,omitempty" url:"maximum_fee_amount,omitempty"`
	ApplicableFeeAmount *Amount `json:"applicable_fee_amount,omitempty" url:"applicable_fee_amount,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) GetFeeAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.FeeAmount
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) GetTaxAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.TaxAmount
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) GetAdditionalFeeAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.AdditionalFeeAmount
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) GetMaximumFeeAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.MaximumFeeAmount
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) GetApplicableFeeAmount() *Amount {
	if c == nil {
		return nil
	}
	return c.ApplicableFeeAmount
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) UnmarshalJSON(data []byte) error {
	type unmarshaler CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CalculateConvenienceFeeResponseDataItemConvenienceFeeBreakdown) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Metadata about the payment method.
type CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata struct {
	// Card network type.
	NetworkType *string `json:"network_type,omitempty" url:"network_type,omitempty"`
	// Type of card.
	CardType *string `json:"card_type,omitempty" url:"card_type,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata) GetNetworkType() *string {
	if c == nil {
		return nil
	}
	return c.NetworkType
}

func (c *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata) GetCardType() *string {
	if c == nil {
		return nil
	}
	return c.CardType
}

func (c *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata) UnmarshalJSON(data []byte) error {
	type unmarshaler CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CalculateConvenienceFeeResponseDataItemPaymentMethodMetadata) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
