// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CreateChallanRequest struct {
	// An object that contains the convenience fee breakdown details.
	ConvenienceFeeBreakdown *CreateChallanRequestConvenienceFeeBreakdown `json:"convenience_fee_breakdown,omitempty" url:"-"`
}

type GetChallanRequest struct {
}

type GetChallanPdfRequest struct {
}

// Response from the Create/Get Challan API.
type ChallanResponse struct {
	// Unique identifier of the challan.
	ChallanID *string `json:"challan_id,omitempty" url:"challan_id,omitempty"`
	// Unique identifier of the order.
	OrderID *string `json:"order_id,omitempty" url:"order_id,omitempty"`
	// Unique customer account identifier.
	VirtualAccountID *string `json:"virtual_account_id,omitempty" url:"virtual_account_id,omitempty"`
	// Account holder's name.
	AccountName *string `json:"account_name,omitempty" url:"account_name,omitempty"`
	// IFSC code of the account.
	AccountIfsc *string `json:"account_ifsc,omitempty" url:"account_ifsc,omitempty"`
	// Name of the bank.
	AccountBankName *string `json:"account_bank_name,omitempty" url:"account_bank_name,omitempty"`
	// Branch of the bank.
	AccountBankBranch *string `json:"account_bank_branch,omitempty" url:"account_bank_branch,omitempty"`
	// URL to download the challan PDF.
	ChallanPdfURL *string `json:"challan_pdf_url,omitempty" url:"challan_pdf_url,omitempty"`
	// Total amount due against the e-challan (in paisa).
	AmountDue *int `json:"amount_due,omitempty" url:"amount_due,omitempty"`
	// Date when the e-challan expires.
	ExpiryDate *string `json:"expiry_date,omitempty" url:"expiry_date,omitempty"`
	// ISO 8601 UTC timestamp when the challan was created.
	CreatedDate *time.Time `json:"created_date,omitempty" url:"created_date,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChallanResponse) GetChallanID() *string {
	if c == nil {
		return nil
	}
	return c.ChallanID
}

func (c *ChallanResponse) GetOrderID() *string {
	if c == nil {
		return nil
	}
	return c.OrderID
}

func (c *ChallanResponse) GetVirtualAccountID() *string {
	if c == nil {
		return nil
	}
	return c.VirtualAccountID
}

func (c *ChallanResponse) GetAccountName() *string {
	if c == nil {
		return nil
	}
	return c.AccountName
}

func (c *ChallanResponse) GetAccountIfsc() *string {
	if c == nil {
		return nil
	}
	return c.AccountIfsc
}

func (c *ChallanResponse) GetAccountBankName() *string {
	if c == nil {
		return nil
	}
	return c.AccountBankName
}

func (c *ChallanResponse) GetAccountBankBranch() *string {
	if c == nil {
		return nil
	}
	return c.AccountBankBranch
}

func (c *ChallanResponse) GetChallanPdfURL() *string {
	if c == nil {
		return nil
	}
	return c.ChallanPdfURL
}

func (c *ChallanResponse) GetAmountDue() *int {
	if c == nil {
		return nil
	}
	return c.AmountDue
}

func (c *ChallanResponse) GetExpiryDate() *string {
	if c == nil {
		return nil
	}
	return c.ExpiryDate
}

func (c *ChallanResponse) GetCreatedDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedDate
}

func (c *ChallanResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChallanResponse) UnmarshalJSON(data []byte) error {
	type embed ChallanResponse
	var unmarshaler = struct {
		embed
		CreatedDate *core.DateTime `json:"created_date,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChallanResponse(unmarshaler.embed)
	c.CreatedDate = unmarshaler.CreatedDate.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChallanResponse) MarshalJSON() ([]byte, error) {
	type embed ChallanResponse
	var marshaler = struct {
		embed
		CreatedDate *core.DateTime `json:"created_date,omitempty"`
	}{
		embed:       embed(*c),
		CreatedDate: core.NewOptionalDateTime(c.CreatedDate),
	}
	return json.Marshal(marshaler)
}

func (c *ChallanResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An object that contains the convenience fee breakdown details.
type CreateChallanRequestConvenienceFeeBreakdown struct {
	// An object that contains the fee amount details.
	FeeAmount *CreateChallanRequestConvenienceFeeBreakdownFeeAmount `json:"fee_amount,omitempty" url:"fee_amount,omitempty"`
	// An object that contains the tax amount details.
	TaxAmount *CreateChallanRequestConvenienceFeeBreakdownTaxAmount `json:"tax_amount,omitempty" url:"tax_amount,omitempty"`
	// An object that contains the additional fee amount details.
	AdditionalFeeAmount *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount `json:"additional_fee_amount,omitempty" url:"additional_fee_amount,omitempty"`
	// An object that contains the maximum fee amount details.
	MaximumFeeAmount *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount `json:"maximum_fee_amount,omitempty" url:"maximum_fee_amount,omitempty"`
	// An object that contains the applicable fee amount details.
	ApplicableFeeAmount *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount `json:"applicable_fee_amount,omitempty" url:"applicable_fee_amount,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) GetFeeAmount() *CreateChallanRequestConvenienceFeeBreakdownFeeAmount {
	if c == nil {
		return nil
	}
	return c.FeeAmount
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) GetTaxAmount() *CreateChallanRequestConvenienceFeeBreakdownTaxAmount {
	if c == nil {
		return nil
	}
	return c.TaxAmount
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) GetAdditionalFeeAmount() *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount {
	if c == nil {
		return nil
	}
	return c.AdditionalFeeAmount
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) GetMaximumFeeAmount() *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount {
	if c == nil {
		return nil
	}
	return c.MaximumFeeAmount
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) GetApplicableFeeAmount() *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount {
	if c == nil {
		return nil
	}
	return c.ApplicableFeeAmount
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChallanRequestConvenienceFeeBreakdown
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateChallanRequestConvenienceFeeBreakdown(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateChallanRequestConvenienceFeeBreakdown) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An object that contains the additional fee amount details.
type CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount struct {
	// The additional fee amount in Paisa.
	// Minimum value: 100 (₹1). Maximum value: 100000000 (₹10 lakh).
	Value *int `json:"value,omitempty" url:"value,omitempty"`
	// Type of currency.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateChallanRequestConvenienceFeeBreakdownAdditionalFeeAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An object that contains the applicable fee amount details.
type CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount struct {
	// The applicable fee amount in Paisa.
	// Minimum value: 100 (₹1). Maximum value: 100000000 (₹10 lakh).
	Value *int `json:"value,omitempty" url:"value,omitempty"`
	// Type of currency.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateChallanRequestConvenienceFeeBreakdownApplicableFeeAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An object that contains the fee amount details.
type CreateChallanRequestConvenienceFeeBreakdownFeeAmount struct {
	// The fee amount in Paisa.
	// Minimum value: 100 (₹1). Maximum value: 100000000 (₹10 lakh).
	Value *int `json:"value,omitempty" url:"value,omitempty"`
	// Type of currency.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateChallanRequestConvenienceFeeBreakdownFeeAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CreateChallanRequestConvenienceFeeBreakdownFeeAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateChallanRequestConvenienceFeeBreakdownFeeAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateChallanRequestConvenienceFeeBreakdownFeeAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChallanRequestConvenienceFeeBreakdownFeeAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateChallanRequestConvenienceFeeBreakdownFeeAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateChallanRequestConvenienceFeeBreakdownFeeAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An object that contains the maximum fee amount details.
type CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount struct {
	// The maximum fee amount in Paisa.
	// Minimum value: 100 (₹1). Maximum value: 100000000 (₹10 lakh).
	Value *int `json:"value,omitempty" url:"value,omitempty"`
	// Type of currency.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateChallanRequestConvenienceFeeBreakdownMaximumFeeAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An object that contains the tax amount details.
type CreateChallanRequestConvenienceFeeBreakdownTaxAmount struct {
	// The tax amount in Paisa.
	// Minimum value: 100 (₹1). Maximum value: 100000000 (₹10 lakh).
	Value *int `json:"value,omitempty" url:"value,omitempty"`
	// Type of currency.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateChallanRequestConvenienceFeeBreakdownTaxAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CreateChallanRequestConvenienceFeeBreakdownTaxAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreateChallanRequestConvenienceFeeBreakdownTaxAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateChallanRequestConvenienceFeeBreakdownTaxAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChallanRequestConvenienceFeeBreakdownTaxAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateChallanRequestConvenienceFeeBreakdownTaxAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateChallanRequestConvenienceFeeBreakdownTaxAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
