// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CurrencyConversionRequest struct {
	// Bank code for the conversion.
	BankCode string `json:"bank_code" url:"-"`
	// Unique invoice reference for the conversion request.
	InvoiceID string `json:"invoice_id" url:"-"`
	// Numeric ISO 4217 code for the source currency (3 digits).
	SourceCurrency string `json:"source_currency" url:"-"`
	// Numeric ISO 4217 code for the destination currency (3 digits).
	DestCurrency string `json:"dest_currency" url:"-"`
	// The transaction amount to convert.
	TransactionAmount string `json:"transaction_amount" url:"-"`
}

// Response from the Currency Conversion API.
type CurrencyConversionResponse struct {
	// Numeric ISO 4217 source currency code.
	SourceCurrency *string `json:"source_currency,omitempty" url:"source_currency,omitempty"`
	// Numeric ISO 4217 destination currency code.
	DestCurrency *string `json:"dest_currency,omitempty" url:"dest_currency,omitempty"`
	// Invoice reference from the request.
	InvoiceID *string `json:"invoice_id,omitempty" url:"invoice_id,omitempty"`
	// Rate used to convert source to destination currency.
	ConversionRate *float64 `json:"conversion_rate,omitempty" url:"conversion_rate,omitempty"`
	// Final amount after conversion and exponent adjustment.
	ConvertedAmount *int `json:"converted_amount,omitempty" url:"converted_amount,omitempty"`
	// Original transaction amount.
	TransactionAmount *string `json:"transaction_amount,omitempty" url:"transaction_amount,omitempty"`
	// Number of decimal places applied during conversion.
	ConvertedExponent *int `json:"converted_exponent,omitempty" url:"converted_exponent,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CurrencyConversionResponse) GetSourceCurrency() *string {
	if c == nil {
		return nil
	}
	return c.SourceCurrency
}

func (c *CurrencyConversionResponse) GetDestCurrency() *string {
	if c == nil {
		return nil
	}
	return c.DestCurrency
}

func (c *CurrencyConversionResponse) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *CurrencyConversionResponse) GetConversionRate() *float64 {
	if c == nil {
		return nil
	}
	return c.ConversionRate
}

func (c *CurrencyConversionResponse) GetConvertedAmount() *int {
	if c == nil {
		return nil
	}
	return c.ConvertedAmount
}

func (c *CurrencyConversionResponse) GetTransactionAmount() *string {
	if c == nil {
		return nil
	}
	return c.TransactionAmount
}

func (c *CurrencyConversionResponse) GetConvertedExponent() *int {
	if c == nil {
		return nil
	}
	return c.ConvertedExponent
}

func (c *CurrencyConversionResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CurrencyConversionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CurrencyConversionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CurrencyConversionResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CurrencyConversionResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
