// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CancelOrderRequest struct {
}

type CaptureOrderRequest struct {
	// Unique identifier for the capture request.
	MerchantCaptureReference string  `json:"merchant_capture_reference" url:"-"`
	CaptureAmount            *Amount `json:"capture_amount,omitempty" url:"-"`
}

type CreateOrderRequest struct {
	// **Idempotency Key.** Unique order reference assigned by the merchant. Duplicate requests with the same `merchant_order_reference` will return the existing order instead of creating a new one.
	MerchantOrderReference string  `json:"merchant_order_reference" url:"-"`
	OrderAmount            *Amount `json:"order_amount,omitempty" url:"-"`
	// Whether pre-authorization is needed.
	PreAuth *bool `json:"pre_auth,omitempty" url:"-"`
	// Payment methods to offer the customer.
	AllowedPaymentMethods []CreateOrderRequestAllowedPaymentMethodsItem `json:"allowed_payment_methods,omitempty" url:"-"`
	// Note to show against the order.
	Notes *string `json:"notes,omitempty" url:"-"`
	// URL to redirect customers after successful payment.
	CallbackURL *string `json:"callback_url,omitempty" url:"-"`
	// URL to redirect customers after failed payment. If not provided, callback_url is used for both.
	FailureCallbackURL *string `json:"failure_callback_url,omitempty" url:"-"`
	// Purchase details including customer information.
	PurchaseDetails *CreateOrderRequestPurchaseDetails `json:"purchase_details,omitempty" url:"-"`
	SplitInfo       *SplitInfo                         `json:"split_info,omitempty" url:"-"`
	// Identifies the order type for MCC transactions. Set to "true" for MCC transactions.
	IsMccTransaction         *string `json:"is_mcc_transaction,omitempty" url:"-"`
	BaseAmount               *Amount `json:"base_amount,omitempty" url:"-"`
	CartCouponDiscountAmount *Amount `json:"cart_coupon_discount_amount,omitempty" url:"-"`
}

type GetOrderByIDRequest struct {
}

type GetOrderByMerchantReferenceRequest struct {
}

type CreateOrderRequestAllowedPaymentMethodsItem string

const (
	CreateOrderRequestAllowedPaymentMethodsItemCard        CreateOrderRequestAllowedPaymentMethodsItem = "CARD"
	CreateOrderRequestAllowedPaymentMethodsItemUpi         CreateOrderRequestAllowedPaymentMethodsItem = "UPI"
	CreateOrderRequestAllowedPaymentMethodsItemNetbanking  CreateOrderRequestAllowedPaymentMethodsItem = "NETBANKING"
	CreateOrderRequestAllowedPaymentMethodsItemPoints      CreateOrderRequestAllowedPaymentMethodsItem = "POINTS"
	CreateOrderRequestAllowedPaymentMethodsItemWallet      CreateOrderRequestAllowedPaymentMethodsItem = "WALLET"
	CreateOrderRequestAllowedPaymentMethodsItemCreditEmi   CreateOrderRequestAllowedPaymentMethodsItem = "CREDIT_EMI"
	CreateOrderRequestAllowedPaymentMethodsItemDebitEmi    CreateOrderRequestAllowedPaymentMethodsItem = "DEBIT_EMI"
	CreateOrderRequestAllowedPaymentMethodsItemBnpl        CreateOrderRequestAllowedPaymentMethodsItem = "BNPL"
	CreateOrderRequestAllowedPaymentMethodsItemCardlessEmi CreateOrderRequestAllowedPaymentMethodsItem = "CARDLESS_EMI"
)

func NewCreateOrderRequestAllowedPaymentMethodsItemFromString(s string) (CreateOrderRequestAllowedPaymentMethodsItem, error) {
	switch s {
	case "CARD":
		return CreateOrderRequestAllowedPaymentMethodsItemCard, nil
	case "UPI":
		return CreateOrderRequestAllowedPaymentMethodsItemUpi, nil
	case "NETBANKING":
		return CreateOrderRequestAllowedPaymentMethodsItemNetbanking, nil
	case "POINTS":
		return CreateOrderRequestAllowedPaymentMethodsItemPoints, nil
	case "WALLET":
		return CreateOrderRequestAllowedPaymentMethodsItemWallet, nil
	case "CREDIT_EMI":
		return CreateOrderRequestAllowedPaymentMethodsItemCreditEmi, nil
	case "DEBIT_EMI":
		return CreateOrderRequestAllowedPaymentMethodsItemDebitEmi, nil
	case "BNPL":
		return CreateOrderRequestAllowedPaymentMethodsItemBnpl, nil
	case "CARDLESS_EMI":
		return CreateOrderRequestAllowedPaymentMethodsItemCardlessEmi, nil
	}
	var t CreateOrderRequestAllowedPaymentMethodsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateOrderRequestAllowedPaymentMethodsItem) Ptr() *CreateOrderRequestAllowedPaymentMethodsItem {
	return &c
}

// Purchase details including customer information.
type CreateOrderRequestPurchaseDetails struct {
	Customer         *CustomerDetails  `json:"customer,omitempty" url:"customer,omitempty"`
	MerchantMetadata *MerchantMetadata `json:"merchant_metadata,omitempty" url:"merchant_metadata,omitempty"`
	CartDetails      *CartDetails      `json:"cart_details,omitempty" url:"cart_details,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateOrderRequestPurchaseDetails) GetCustomer() *CustomerDetails {
	if c == nil {
		return nil
	}
	return c.Customer
}

func (c *CreateOrderRequestPurchaseDetails) GetMerchantMetadata() *MerchantMetadata {
	if c == nil {
		return nil
	}
	return c.MerchantMetadata
}

func (c *CreateOrderRequestPurchaseDetails) GetCartDetails() *CartDetails {
	if c == nil {
		return nil
	}
	return c.CartDetails
}

func (c *CreateOrderRequestPurchaseDetails) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateOrderRequestPurchaseDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateOrderRequestPurchaseDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateOrderRequestPurchaseDetails(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateOrderRequestPurchaseDetails) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
