// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CheckPointBalanceRequest struct {
	// Payment option details for the points balance check.
	PaymentOption *CheckPointBalanceRequestPaymentOption `json:"payment_option,omitempty" url:"-"`
	// Order details for the points balance check.
	OrderDetails *CheckPointBalanceRequestOrderDetails `json:"order_details,omitempty" url:"-"`
}

// Response from the Check Point Balance API.
type CheckPointBalanceResponse struct {
	// Card balance details.
	Balance *CheckPointBalanceResponseBalance `json:"balance,omitempty" url:"balance,omitempty"`
	// Redeemable amount details.
	RedeemableAmount *CheckPointBalanceResponseRedeemableAmount `json:"redeemable_amount,omitempty" url:"redeemable_amount,omitempty"`
	// Total redeemable points available on the card.
	RedeemablePoints *int `json:"redeemable_points,omitempty" url:"redeemable_points,omitempty"`
	// Card eligibility status for pay by points.
	IsEligible *bool `json:"is_eligible,omitempty" url:"is_eligible,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceResponse) GetBalance() *CheckPointBalanceResponseBalance {
	if c == nil {
		return nil
	}
	return c.Balance
}

func (c *CheckPointBalanceResponse) GetRedeemableAmount() *CheckPointBalanceResponseRedeemableAmount {
	if c == nil {
		return nil
	}
	return c.RedeemableAmount
}

func (c *CheckPointBalanceResponse) GetRedeemablePoints() *int {
	if c == nil {
		return nil
	}
	return c.RedeemablePoints
}

func (c *CheckPointBalanceResponse) GetIsEligible() *bool {
	if c == nil {
		return nil
	}
	return c.IsEligible
}

func (c *CheckPointBalanceResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Card balance details.
type CheckPointBalanceResponseBalance struct {
	// Balance available on the card (in paisa).
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceResponseBalance) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CheckPointBalanceResponseBalance) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CheckPointBalanceResponseBalance) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceResponseBalance) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceResponseBalance
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceResponseBalance(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceResponseBalance) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Redeemable amount details.
type CheckPointBalanceResponseRedeemableAmount struct {
	// Redeemable amount on card (in paisa).
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceResponseRedeemableAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CheckPointBalanceResponseRedeemableAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CheckPointBalanceResponseRedeemableAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceResponseRedeemableAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceResponseRedeemableAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceResponseRedeemableAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceResponseRedeemableAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Order details for the points balance check.
type CheckPointBalanceRequestOrderDetails struct {
	// Order amount for the points balance check.
	OrderAmount *CheckPointBalanceRequestOrderDetailsOrderAmount `json:"order_amount,omitempty" url:"order_amount,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceRequestOrderDetails) GetOrderAmount() *CheckPointBalanceRequestOrderDetailsOrderAmount {
	if c == nil {
		return nil
	}
	return c.OrderAmount
}

func (c *CheckPointBalanceRequestOrderDetails) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceRequestOrderDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceRequestOrderDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceRequestOrderDetails(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceRequestOrderDetails) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Order amount for the points balance check.
type CheckPointBalanceRequestOrderDetailsOrderAmount struct {
	// Order amount in smallest currency unit (e.g., paisa).
	Value *int `json:"value,omitempty" url:"value,omitempty"`
	// Currency code.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceRequestOrderDetailsOrderAmount) GetValue() *int {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CheckPointBalanceRequestOrderDetailsOrderAmount) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CheckPointBalanceRequestOrderDetailsOrderAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceRequestOrderDetailsOrderAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceRequestOrderDetailsOrderAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceRequestOrderDetailsOrderAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceRequestOrderDetailsOrderAmount) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Payment option details for the points balance check.
type CheckPointBalanceRequestPaymentOption struct {
	PointsCardDetails *CheckPointBalanceRequestPaymentOptionPointsCardDetails `json:"points_card_details,omitempty" url:"points_card_details,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceRequestPaymentOption) GetPointsCardDetails() *CheckPointBalanceRequestPaymentOptionPointsCardDetails {
	if c == nil {
		return nil
	}
	return c.PointsCardDetails
}

func (c *CheckPointBalanceRequestPaymentOption) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceRequestPaymentOption) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceRequestPaymentOption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceRequestPaymentOption(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceRequestPaymentOption) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CheckPointBalanceRequestPaymentOptionPointsCardDetails struct {
	// Last four digits of the card.
	CardLast4 *string `json:"card_last4,omitempty" url:"card_last4,omitempty"`
	// Card number to check points balance.
	CardNumber *string `json:"card_number,omitempty" url:"card_number,omitempty"`
	// Registered mobile number on the card.
	RegisteredMobileNumber *string `json:"registered_mobile_number,omitempty" url:"registered_mobile_number,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckPointBalanceRequestPaymentOptionPointsCardDetails) GetCardLast4() *string {
	if c == nil {
		return nil
	}
	return c.CardLast4
}

func (c *CheckPointBalanceRequestPaymentOptionPointsCardDetails) GetCardNumber() *string {
	if c == nil {
		return nil
	}
	return c.CardNumber
}

func (c *CheckPointBalanceRequestPaymentOptionPointsCardDetails) GetRegisteredMobileNumber() *string {
	if c == nil {
		return nil
	}
	return c.RegisteredMobileNumber
}

func (c *CheckPointBalanceRequestPaymentOptionPointsCardDetails) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckPointBalanceRequestPaymentOptionPointsCardDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckPointBalanceRequestPaymentOptionPointsCardDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckPointBalanceRequestPaymentOptionPointsCardDetails(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckPointBalanceRequestPaymentOptionPointsCardDetails) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
