// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CancelScheduledPayoutRequest struct {
}

type CreateBulkPayoutRequest struct {
	// File containing beneficiary account details for bulk payout processing.
	File string `json:"file" url:"-"`
}

type CreatePayoutRequest struct {
	// Unique identifier to track the payout. Must not contain spaces. **Acts as the idempotency key** — duplicate requests with the same `clientReferenceId` will not create a new payout.
	ClientReferenceID string `json:"clientReferenceId" url:"-"`
	// Name of the beneficiary's bank account holder. Alphabets and spaces only.
	PayeeName string `json:"payeeName" url:"-"`
	// Email address of the beneficiary.
	Email *string `json:"email,omitempty" url:"-"`
	// Mobile number of the beneficiary (10 numeric digits).
	Phone *string `json:"phone,omitempty" url:"-"`
	// Beneficiary's bank account number. Mandatory for IMPS, NEFT, and RTGS.
	AccountNumber *string `json:"accountNumber,omitempty" url:"-"`
	// Beneficiary's bank IFSC code. Mandatory for IMPS, NEFT, and RTGS.
	// First 4 characters alphabets, 5th character must be 0, remaining alphanumeric.
	BranchCode *string       `json:"branchCode,omitempty" url:"-"`
	Amount     *PayoutAmount `json:"amount,omitempty" url:"-"`
	// Mode of payment for the payout.
	Mode CreatePayoutRequestMode `json:"mode" url:"-"`
	// Description or reference text for the transaction. Supported characters A-Z, a-z, 0-9, hyphen, space.
	Remarks string `json:"remarks" url:"-"`
}

type ListPayoutsRequest struct {
	// Unique identifier of the payment in Pine Labs database.
	PaymentReferenceID *string `json:"-" url:"paymentReferenceId,omitempty"`
	// Unique client reference provided when creating the payout.
	ClientReferenceID *string `json:"-" url:"clientReferenceId,omitempty"`
	// Unique identifier of the request in Pine Labs database.
	RequestReferenceID *string `json:"-" url:"requestReferenceId,omitempty"`
	// Unique Transaction Reference (UTR) from the bank.
	BankTransactionReferenceID *string `json:"-" url:"bankTransactionReferenceId,omitempty"`
	// Filter by payment mode.
	Mode *ListPayoutsRequestMode `json:"-" url:"mode,omitempty"`
	// Fetch payouts initiated after this date (ISO 8601 UTC).
	DateFrom *time.Time `json:"-" url:"dateFrom,omitempty"`
	// Fetch payouts initiated before this date (ISO 8601 UTC).
	DateTo *time.Time `json:"-" url:"dateTo,omitempty"`
	// Filter by payout status.
	Status *ListPayoutsRequestStatus `json:"-" url:"status,omitempty"`
	// Page number (default 1).
	Page *string `json:"-" url:"page,omitempty"`
	// Number of records per page.
	Count *string `json:"-" url:"count,omitempty"`
}

type UpdateScheduledPayoutRequest struct {
	// New scheduled time for executing the payout (ISO 8601 UTC).
	ScheduleAt *time.Time `json:"scheduleAt,omitempty" url:"-"`
}

func (u *UpdateScheduledPayoutRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateScheduledPayoutRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateScheduledPayoutRequest(body)
	return nil
}

func (u *UpdateScheduledPayoutRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateScheduledPayoutRequest
	var marshaler = struct {
		embed
		ScheduleAt *core.DateTime `json:"scheduleAt,omitempty"`
	}{
		embed:      embed(*u),
		ScheduleAt: core.NewOptionalDateTime(u.ScheduleAt),
	}
	return json.Marshal(marshaler)
}

// Response returned after creating a bulk payout via file upload.
type CreateBulkPayoutResponse struct {
	// Unique identifier of the bulk request in Pine Labs database.
	RequestReferenceID *string `json:"requestReferenceId,omitempty" url:"requestReferenceId,omitempty"`
	// Bulk payout processing status.
	Status *CreateBulkPayoutResponseStatus `json:"status,omitempty" url:"status,omitempty"`
	// Message corresponding to the bulk payout status.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// HATEOAS navigation links.
	Links []*PayoutLink `json:"_links,omitempty" url:"_links,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateBulkPayoutResponse) GetRequestReferenceID() *string {
	if c == nil {
		return nil
	}
	return c.RequestReferenceID
}

func (c *CreateBulkPayoutResponse) GetStatus() *CreateBulkPayoutResponseStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreateBulkPayoutResponse) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateBulkPayoutResponse) GetLinks() []*PayoutLink {
	if c == nil {
		return nil
	}
	return c.Links
}

func (c *CreateBulkPayoutResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateBulkPayoutResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateBulkPayoutResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateBulkPayoutResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateBulkPayoutResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Bulk payout processing status.
type CreateBulkPayoutResponseStatus string

const (
	CreateBulkPayoutResponseStatusScheduled  CreateBulkPayoutResponseStatus = "SCHEDULED"
	CreateBulkPayoutResponseStatusPending    CreateBulkPayoutResponseStatus = "PENDING"
	CreateBulkPayoutResponseStatusProcessing CreateBulkPayoutResponseStatus = "PROCESSING"
	CreateBulkPayoutResponseStatusProcessed  CreateBulkPayoutResponseStatus = "PROCESSED"
	CreateBulkPayoutResponseStatusSuccess    CreateBulkPayoutResponseStatus = "SUCCESS"
	CreateBulkPayoutResponseStatusFailed     CreateBulkPayoutResponseStatus = "FAILED"
)

func NewCreateBulkPayoutResponseStatusFromString(s string) (CreateBulkPayoutResponseStatus, error) {
	switch s {
	case "SCHEDULED":
		return CreateBulkPayoutResponseStatusScheduled, nil
	case "PENDING":
		return CreateBulkPayoutResponseStatusPending, nil
	case "PROCESSING":
		return CreateBulkPayoutResponseStatusProcessing, nil
	case "PROCESSED":
		return CreateBulkPayoutResponseStatusProcessed, nil
	case "SUCCESS":
		return CreateBulkPayoutResponseStatusSuccess, nil
	case "FAILED":
		return CreateBulkPayoutResponseStatusFailed, nil
	}
	var t CreateBulkPayoutResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateBulkPayoutResponseStatus) Ptr() *CreateBulkPayoutResponseStatus {
	return &c
}

// Response returned after creating a payout.
type CreatePayoutResponse struct {
	// Unique identifier to track the payout.
	ClientReferenceID *string `json:"clientReferenceId,omitempty" url:"clientReferenceId,omitempty"`
	// Unique identifier of the request in Pine Labs database.
	RequestReferenceID *string `json:"requestReferenceId,omitempty" url:"requestReferenceId,omitempty"`
	// Unique identifier of the payment in Pine Labs database.
	PaymentReferenceID *string `json:"paymentReferenceId,omitempty" url:"paymentReferenceId,omitempty"`
	// Name of the beneficiary.
	PayeeName *string `json:"payeeName,omitempty" url:"payeeName,omitempty"`
	// Masked account number of the beneficiary.
	AccountNumber *string `json:"accountNumber,omitempty" url:"accountNumber,omitempty"`
	// IFSC code of the beneficiary's bank.
	BranchCode *string       `json:"branchCode,omitempty" url:"branchCode,omitempty"`
	Amount     *PayoutAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Payment mode used for the payout.
	Mode *CreatePayoutResponseMode `json:"mode,omitempty" url:"mode,omitempty"`
	// Current payout status.
	// - SCHEDULED: Request successfully received.
	// - PENDING: Funding account has insufficient balance.
	// - PROCESSING: Sent to bank, not yet processed.
	// - PROCESSED: Bank processed, confirmation pending.
	// - SUCCESS: Amount debited and credited successfully.
	// - FAILED: Transaction failed.
	Status *CreatePayoutResponseStatus `json:"status,omitempty" url:"status,omitempty"`
	// Message corresponding to the payout status.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Scheduled execution time in UTC.
	ScheduledAt *time.Time `json:"scheduledAt,omitempty" url:"scheduledAt,omitempty"`
	// Description or reference text for the transaction.
	Remarks *string `json:"remarks,omitempty" url:"remarks,omitempty"`
	// HATEOAS navigation links.
	Links []*PayoutLink `json:"_links,omitempty" url:"_links,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreatePayoutResponse) GetClientReferenceID() *string {
	if c == nil {
		return nil
	}
	return c.ClientReferenceID
}

func (c *CreatePayoutResponse) GetRequestReferenceID() *string {
	if c == nil {
		return nil
	}
	return c.RequestReferenceID
}

func (c *CreatePayoutResponse) GetPaymentReferenceID() *string {
	if c == nil {
		return nil
	}
	return c.PaymentReferenceID
}

func (c *CreatePayoutResponse) GetPayeeName() *string {
	if c == nil {
		return nil
	}
	return c.PayeeName
}

func (c *CreatePayoutResponse) GetAccountNumber() *string {
	if c == nil {
		return nil
	}
	return c.AccountNumber
}

func (c *CreatePayoutResponse) GetBranchCode() *string {
	if c == nil {
		return nil
	}
	return c.BranchCode
}

func (c *CreatePayoutResponse) GetAmount() *PayoutAmount {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CreatePayoutResponse) GetMode() *CreatePayoutResponseMode {
	if c == nil {
		return nil
	}
	return c.Mode
}

func (c *CreatePayoutResponse) GetStatus() *CreatePayoutResponseStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreatePayoutResponse) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreatePayoutResponse) GetScheduledAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ScheduledAt
}

func (c *CreatePayoutResponse) GetRemarks() *string {
	if c == nil {
		return nil
	}
	return c.Remarks
}

func (c *CreatePayoutResponse) GetLinks() []*PayoutLink {
	if c == nil {
		return nil
	}
	return c.Links
}

func (c *CreatePayoutResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreatePayoutResponse) UnmarshalJSON(data []byte) error {
	type embed CreatePayoutResponse
	var unmarshaler = struct {
		embed
		ScheduledAt *core.DateTime `json:"scheduledAt,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreatePayoutResponse(unmarshaler.embed)
	c.ScheduledAt = unmarshaler.ScheduledAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePayoutResponse) MarshalJSON() ([]byte, error) {
	type embed CreatePayoutResponse
	var marshaler = struct {
		embed
		ScheduledAt *core.DateTime `json:"scheduledAt,omitempty"`
	}{
		embed:       embed(*c),
		ScheduledAt: core.NewOptionalDateTime(c.ScheduledAt),
	}
	return json.Marshal(marshaler)
}

func (c *CreatePayoutResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Payment mode used for the payout.
type CreatePayoutResponseMode string

const (
	CreatePayoutResponseModeUpi  CreatePayoutResponseMode = "UPI"
	CreatePayoutResponseModeImps CreatePayoutResponseMode = "IMPS"
	CreatePayoutResponseModeNeft CreatePayoutResponseMode = "NEFT"
	CreatePayoutResponseModeRtgs CreatePayoutResponseMode = "RTGS"
)

func NewCreatePayoutResponseModeFromString(s string) (CreatePayoutResponseMode, error) {
	switch s {
	case "UPI":
		return CreatePayoutResponseModeUpi, nil
	case "IMPS":
		return CreatePayoutResponseModeImps, nil
	case "NEFT":
		return CreatePayoutResponseModeNeft, nil
	case "RTGS":
		return CreatePayoutResponseModeRtgs, nil
	}
	var t CreatePayoutResponseMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePayoutResponseMode) Ptr() *CreatePayoutResponseMode {
	return &c
}

// Current payout status.
// - SCHEDULED: Request successfully received.
// - PENDING: Funding account has insufficient balance.
// - PROCESSING: Sent to bank, not yet processed.
// - PROCESSED: Bank processed, confirmation pending.
// - SUCCESS: Amount debited and credited successfully.
// - FAILED: Transaction failed.
type CreatePayoutResponseStatus string

const (
	CreatePayoutResponseStatusScheduled  CreatePayoutResponseStatus = "SCHEDULED"
	CreatePayoutResponseStatusPending    CreatePayoutResponseStatus = "PENDING"
	CreatePayoutResponseStatusProcessing CreatePayoutResponseStatus = "PROCESSING"
	CreatePayoutResponseStatusProcessed  CreatePayoutResponseStatus = "PROCESSED"
	CreatePayoutResponseStatusSuccess    CreatePayoutResponseStatus = "SUCCESS"
	CreatePayoutResponseStatusFailed     CreatePayoutResponseStatus = "FAILED"
)

func NewCreatePayoutResponseStatusFromString(s string) (CreatePayoutResponseStatus, error) {
	switch s {
	case "SCHEDULED":
		return CreatePayoutResponseStatusScheduled, nil
	case "PENDING":
		return CreatePayoutResponseStatusPending, nil
	case "PROCESSING":
		return CreatePayoutResponseStatusProcessing, nil
	case "PROCESSED":
		return CreatePayoutResponseStatusProcessed, nil
	case "SUCCESS":
		return CreatePayoutResponseStatusSuccess, nil
	case "FAILED":
		return CreatePayoutResponseStatusFailed, nil
	}
	var t CreatePayoutResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePayoutResponseStatus) Ptr() *CreatePayoutResponseStatus {
	return &c
}

// Response returned for the funding account balance inquiry.
type GetAccountBalanceResponse struct {
	// Funding account number.
	AccountNumber *string `json:"accountNumber,omitempty" url:"accountNumber,omitempty"`
	// IFSC code of the funding account bank.
	BranchCode *string       `json:"branchCode,omitempty" url:"branchCode,omitempty"`
	Balance    *SimpleAmount `json:"balance,omitempty" url:"balance,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetAccountBalanceResponse) GetAccountNumber() *string {
	if g == nil {
		return nil
	}
	return g.AccountNumber
}

func (g *GetAccountBalanceResponse) GetBranchCode() *string {
	if g == nil {
		return nil
	}
	return g.BranchCode
}

func (g *GetAccountBalanceResponse) GetBalance() *SimpleAmount {
	if g == nil {
		return nil
	}
	return g.Balance
}

func (g *GetAccountBalanceResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetAccountBalanceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAccountBalanceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAccountBalanceResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAccountBalanceResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Individual payout record returned in the Get Payouts list response.
type GetPayoutsPaymentItem struct {
	// Unique identifier to track the payout.
	ClientReferenceID *string `json:"clientReferenceId,omitempty" url:"clientReferenceId,omitempty"`
	// Unique identifier of the payment in Pine Labs database.
	PaymentReferenceID *string `json:"paymentReferenceId,omitempty" url:"paymentReferenceId,omitempty"`
	// Unique Transaction Reference (UTR) from the bank.
	BankTransactionReferenceID *string `json:"bankTransactionReferenceId,omitempty" url:"bankTransactionReferenceId,omitempty"`
	// Payment mode used for the payout.
	Mode   *GetPayoutsPaymentItemMode `json:"mode,omitempty" url:"mode,omitempty"`
	Amount *PayoutAmount              `json:"amount,omitempty" url:"amount,omitempty"`
	// Beneficiary's bank account number (may be masked).
	AccountNumber *string `json:"accountNumber,omitempty" url:"accountNumber,omitempty"`
	// Name of the beneficiary.
	PayeeName *string       `json:"payeeName,omitempty" url:"payeeName,omitempty"`
	Fees      *SimpleAmount `json:"fees,omitempty" url:"fees,omitempty"`
	Tax       *SimpleAmount `json:"tax,omitempty" url:"tax,omitempty"`
	// Description or reference text for the transaction.
	Remarks *string `json:"remarks,omitempty" url:"remarks,omitempty"`
	// Current payout status.
	Status *GetPayoutsPaymentItemStatus `json:"status,omitempty" url:"status,omitempty"`
	// Message corresponding to the payout status.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Timestamp when the payout request was received (ISO 8601 UTC).
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	// Timestamp when the payout record was last updated (ISO 8601 UTC).
	UpdatedAt *time.Time `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`
	// Scheduled execution time in UTC.
	ScheduledAt *time.Time `json:"scheduledAt,omitempty" url:"scheduledAt,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetPayoutsPaymentItem) GetClientReferenceID() *string {
	if g == nil {
		return nil
	}
	return g.ClientReferenceID
}

func (g *GetPayoutsPaymentItem) GetPaymentReferenceID() *string {
	if g == nil {
		return nil
	}
	return g.PaymentReferenceID
}

func (g *GetPayoutsPaymentItem) GetBankTransactionReferenceID() *string {
	if g == nil {
		return nil
	}
	return g.BankTransactionReferenceID
}

func (g *GetPayoutsPaymentItem) GetMode() *GetPayoutsPaymentItemMode {
	if g == nil {
		return nil
	}
	return g.Mode
}

func (g *GetPayoutsPaymentItem) GetAmount() *PayoutAmount {
	if g == nil {
		return nil
	}
	return g.Amount
}

func (g *GetPayoutsPaymentItem) GetAccountNumber() *string {
	if g == nil {
		return nil
	}
	return g.AccountNumber
}

func (g *GetPayoutsPaymentItem) GetPayeeName() *string {
	if g == nil {
		return nil
	}
	return g.PayeeName
}

func (g *GetPayoutsPaymentItem) GetFees() *SimpleAmount {
	if g == nil {
		return nil
	}
	return g.Fees
}

func (g *GetPayoutsPaymentItem) GetTax() *SimpleAmount {
	if g == nil {
		return nil
	}
	return g.Tax
}

func (g *GetPayoutsPaymentItem) GetRemarks() *string {
	if g == nil {
		return nil
	}
	return g.Remarks
}

func (g *GetPayoutsPaymentItem) GetStatus() *GetPayoutsPaymentItemStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetPayoutsPaymentItem) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetPayoutsPaymentItem) GetCreatedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GetPayoutsPaymentItem) GetUpdatedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.UpdatedAt
}

func (g *GetPayoutsPaymentItem) GetScheduledAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ScheduledAt
}

func (g *GetPayoutsPaymentItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPayoutsPaymentItem) UnmarshalJSON(data []byte) error {
	type embed GetPayoutsPaymentItem
	var unmarshaler = struct {
		embed
		CreatedAt   *core.DateTime `json:"createdAt,omitempty"`
		UpdatedAt   *core.DateTime `json:"updatedAt,omitempty"`
		ScheduledAt *core.DateTime `json:"scheduledAt,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetPayoutsPaymentItem(unmarshaler.embed)
	g.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	g.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	g.ScheduledAt = unmarshaler.ScheduledAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPayoutsPaymentItem) MarshalJSON() ([]byte, error) {
	type embed GetPayoutsPaymentItem
	var marshaler = struct {
		embed
		CreatedAt   *core.DateTime `json:"createdAt,omitempty"`
		UpdatedAt   *core.DateTime `json:"updatedAt,omitempty"`
		ScheduledAt *core.DateTime `json:"scheduledAt,omitempty"`
	}{
		embed:       embed(*g),
		CreatedAt:   core.NewOptionalDateTime(g.CreatedAt),
		UpdatedAt:   core.NewOptionalDateTime(g.UpdatedAt),
		ScheduledAt: core.NewOptionalDateTime(g.ScheduledAt),
	}
	return json.Marshal(marshaler)
}

func (g *GetPayoutsPaymentItem) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Payment mode used for the payout.
type GetPayoutsPaymentItemMode string

const (
	GetPayoutsPaymentItemModeUpi  GetPayoutsPaymentItemMode = "UPI"
	GetPayoutsPaymentItemModeImps GetPayoutsPaymentItemMode = "IMPS"
	GetPayoutsPaymentItemModeNeft GetPayoutsPaymentItemMode = "NEFT"
	GetPayoutsPaymentItemModeRtgs GetPayoutsPaymentItemMode = "RTGS"
)

func NewGetPayoutsPaymentItemModeFromString(s string) (GetPayoutsPaymentItemMode, error) {
	switch s {
	case "UPI":
		return GetPayoutsPaymentItemModeUpi, nil
	case "IMPS":
		return GetPayoutsPaymentItemModeImps, nil
	case "NEFT":
		return GetPayoutsPaymentItemModeNeft, nil
	case "RTGS":
		return GetPayoutsPaymentItemModeRtgs, nil
	}
	var t GetPayoutsPaymentItemMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetPayoutsPaymentItemMode) Ptr() *GetPayoutsPaymentItemMode {
	return &g
}

// Current payout status.
type GetPayoutsPaymentItemStatus string

const (
	GetPayoutsPaymentItemStatusScheduled  GetPayoutsPaymentItemStatus = "SCHEDULED"
	GetPayoutsPaymentItemStatusPending    GetPayoutsPaymentItemStatus = "PENDING"
	GetPayoutsPaymentItemStatusProcessing GetPayoutsPaymentItemStatus = "PROCESSING"
	GetPayoutsPaymentItemStatusProcessed  GetPayoutsPaymentItemStatus = "PROCESSED"
	GetPayoutsPaymentItemStatusSuccess    GetPayoutsPaymentItemStatus = "SUCCESS"
	GetPayoutsPaymentItemStatusFailed     GetPayoutsPaymentItemStatus = "FAILED"
)

func NewGetPayoutsPaymentItemStatusFromString(s string) (GetPayoutsPaymentItemStatus, error) {
	switch s {
	case "SCHEDULED":
		return GetPayoutsPaymentItemStatusScheduled, nil
	case "PENDING":
		return GetPayoutsPaymentItemStatusPending, nil
	case "PROCESSING":
		return GetPayoutsPaymentItemStatusProcessing, nil
	case "PROCESSED":
		return GetPayoutsPaymentItemStatusProcessed, nil
	case "SUCCESS":
		return GetPayoutsPaymentItemStatusSuccess, nil
	case "FAILED":
		return GetPayoutsPaymentItemStatusFailed, nil
	}
	var t GetPayoutsPaymentItemStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetPayoutsPaymentItemStatus) Ptr() *GetPayoutsPaymentItemStatus {
	return &g
}

// Response returned when listing payouts.
type GetPayoutsResponse struct {
	// List of payout records matching the query.
	Payments []*GetPayoutsPaymentItem `json:"payments,omitempty" url:"payments,omitempty"`
	// Total number of records matching the query.
	TotalRecords *int `json:"totalRecords,omitempty" url:"totalRecords,omitempty"`
	// Next page number in the result set.
	NextPage *int `json:"nextPage,omitempty" url:"nextPage,omitempty"`
	// Total number of pages in the result set.
	TotalPages *int `json:"totalPages,omitempty" url:"totalPages,omitempty"`
	// HATEOAS pagination links.
	Links []*PayoutLink `json:"_links,omitempty" url:"_links,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetPayoutsResponse) GetPayments() []*GetPayoutsPaymentItem {
	if g == nil {
		return nil
	}
	return g.Payments
}

func (g *GetPayoutsResponse) GetTotalRecords() *int {
	if g == nil {
		return nil
	}
	return g.TotalRecords
}

func (g *GetPayoutsResponse) GetNextPage() *int {
	if g == nil {
		return nil
	}
	return g.NextPage
}

func (g *GetPayoutsResponse) GetTotalPages() *int {
	if g == nil {
		return nil
	}
	return g.TotalPages
}

func (g *GetPayoutsResponse) GetLinks() []*PayoutLink {
	if g == nil {
		return nil
	}
	return g.Links
}

func (g *GetPayoutsResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPayoutsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPayoutsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPayoutsResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPayoutsResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Payout monetary amount with currency. For payout creation, minimum ₹1 (100 paisa), maximum ₹10 lakh (100000000 paisa).
type PayoutAmount struct {
	// Amount in the smallest currency unit (paisa for INR). Minimum ₹1 (100), maximum ₹10 lakh (100000000).
	Value int `json:"value" url:"value"`
	// Three-letter ISO 4217 currency code.
	Currency string `json:"currency" url:"currency"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutAmount) GetValue() int {
	if p == nil {
		return 0
	}
	return p.Value
}

func (p *PayoutAmount) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *PayoutAmount) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutAmount) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Full payout detail returned in update/cancel and get-by-reference responses.
type PayoutDetail struct {
	// Unique identifier to track the payout.
	ClientReferenceID *string `json:"clientReferenceId,omitempty" url:"clientReferenceId,omitempty"`
	// Unique identifier of the request in Pine Labs database.
	RequestReferenceID *string `json:"requestReferenceId,omitempty" url:"requestReferenceId,omitempty"`
	// Unique identifier of the payment in Pine Labs database.
	PaymentReferenceID *string `json:"paymentReferenceId,omitempty" url:"paymentReferenceId,omitempty"`
	// Name of the beneficiary.
	PayeeName *string `json:"payeeName,omitempty" url:"payeeName,omitempty"`
	// Beneficiary's bank account number (may be masked).
	AccountNumber *string `json:"accountNumber,omitempty" url:"accountNumber,omitempty"`
	// IFSC code of the beneficiary's bank.
	BranchCode *string `json:"branchCode,omitempty" url:"branchCode,omitempty"`
	// VPA handle of the beneficiary (for UPI payouts).
	Vpa *string `json:"vpa,omitempty" url:"vpa,omitempty"`
	// Email address of the beneficiary.
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Mobile number of the beneficiary.
	Phone  *string       `json:"phone,omitempty" url:"phone,omitempty"`
	Amount *PayoutAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Payment mode used for the payout.
	Mode *PayoutDetailMode `json:"mode,omitempty" url:"mode,omitempty"`
	// Current payout status.
	// - SCHEDULED: Request successfully received.
	// - PENDING: Funding account has insufficient balance.
	// - PROCESSING: Sent to bank, not yet processed.
	// - PROCESSED: Bank processed, confirmation pending.
	// - SUCCESS: Amount debited and credited successfully.
	// - FAILED: Transaction failed.
	Status *PayoutDetailStatus `json:"status,omitempty" url:"status,omitempty"`
	// Message corresponding to the payout status.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Scheduled execution time in UTC. Empty string when cancelled.
	ScheduledAt *time.Time `json:"scheduledAt,omitempty" url:"scheduledAt,omitempty"`
	// Description or reference text for the transaction.
	Remarks *string `json:"remarks,omitempty" url:"remarks,omitempty"`
	// HATEOAS navigation links.
	Links []*PayoutLink `json:"_links,omitempty" url:"_links,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutDetail) GetClientReferenceID() *string {
	if p == nil {
		return nil
	}
	return p.ClientReferenceID
}

func (p *PayoutDetail) GetRequestReferenceID() *string {
	if p == nil {
		return nil
	}
	return p.RequestReferenceID
}

func (p *PayoutDetail) GetPaymentReferenceID() *string {
	if p == nil {
		return nil
	}
	return p.PaymentReferenceID
}

func (p *PayoutDetail) GetPayeeName() *string {
	if p == nil {
		return nil
	}
	return p.PayeeName
}

func (p *PayoutDetail) GetAccountNumber() *string {
	if p == nil {
		return nil
	}
	return p.AccountNumber
}

func (p *PayoutDetail) GetBranchCode() *string {
	if p == nil {
		return nil
	}
	return p.BranchCode
}

func (p *PayoutDetail) GetVpa() *string {
	if p == nil {
		return nil
	}
	return p.Vpa
}

func (p *PayoutDetail) GetEmail() *string {
	if p == nil {
		return nil
	}
	return p.Email
}

func (p *PayoutDetail) GetPhone() *string {
	if p == nil {
		return nil
	}
	return p.Phone
}

func (p *PayoutDetail) GetAmount() *PayoutAmount {
	if p == nil {
		return nil
	}
	return p.Amount
}

func (p *PayoutDetail) GetMode() *PayoutDetailMode {
	if p == nil {
		return nil
	}
	return p.Mode
}

func (p *PayoutDetail) GetStatus() *PayoutDetailStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PayoutDetail) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

func (p *PayoutDetail) GetScheduledAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.ScheduledAt
}

func (p *PayoutDetail) GetRemarks() *string {
	if p == nil {
		return nil
	}
	return p.Remarks
}

func (p *PayoutDetail) GetLinks() []*PayoutLink {
	if p == nil {
		return nil
	}
	return p.Links
}

func (p *PayoutDetail) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutDetail) UnmarshalJSON(data []byte) error {
	type embed PayoutDetail
	var unmarshaler = struct {
		embed
		ScheduledAt *core.DateTime `json:"scheduledAt,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PayoutDetail(unmarshaler.embed)
	p.ScheduledAt = unmarshaler.ScheduledAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutDetail) MarshalJSON() ([]byte, error) {
	type embed PayoutDetail
	var marshaler = struct {
		embed
		ScheduledAt *core.DateTime `json:"scheduledAt,omitempty"`
	}{
		embed:       embed(*p),
		ScheduledAt: core.NewOptionalDateTime(p.ScheduledAt),
	}
	return json.Marshal(marshaler)
}

func (p *PayoutDetail) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Payment mode used for the payout.
type PayoutDetailMode string

const (
	PayoutDetailModeUpi  PayoutDetailMode = "UPI"
	PayoutDetailModeImps PayoutDetailMode = "IMPS"
	PayoutDetailModeNeft PayoutDetailMode = "NEFT"
	PayoutDetailModeRtgs PayoutDetailMode = "RTGS"
)

func NewPayoutDetailModeFromString(s string) (PayoutDetailMode, error) {
	switch s {
	case "UPI":
		return PayoutDetailModeUpi, nil
	case "IMPS":
		return PayoutDetailModeImps, nil
	case "NEFT":
		return PayoutDetailModeNeft, nil
	case "RTGS":
		return PayoutDetailModeRtgs, nil
	}
	var t PayoutDetailMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PayoutDetailMode) Ptr() *PayoutDetailMode {
	return &p
}

// Current payout status.
// - SCHEDULED: Request successfully received.
// - PENDING: Funding account has insufficient balance.
// - PROCESSING: Sent to bank, not yet processed.
// - PROCESSED: Bank processed, confirmation pending.
// - SUCCESS: Amount debited and credited successfully.
// - FAILED: Transaction failed.
type PayoutDetailStatus string

const (
	PayoutDetailStatusScheduled  PayoutDetailStatus = "SCHEDULED"
	PayoutDetailStatusPending    PayoutDetailStatus = "PENDING"
	PayoutDetailStatusProcessing PayoutDetailStatus = "PROCESSING"
	PayoutDetailStatusProcessed  PayoutDetailStatus = "PROCESSED"
	PayoutDetailStatusSuccess    PayoutDetailStatus = "SUCCESS"
	PayoutDetailStatusFailed     PayoutDetailStatus = "FAILED"
)

func NewPayoutDetailStatusFromString(s string) (PayoutDetailStatus, error) {
	switch s {
	case "SCHEDULED":
		return PayoutDetailStatusScheduled, nil
	case "PENDING":
		return PayoutDetailStatusPending, nil
	case "PROCESSING":
		return PayoutDetailStatusProcessing, nil
	case "PROCESSED":
		return PayoutDetailStatusProcessed, nil
	case "SUCCESS":
		return PayoutDetailStatusSuccess, nil
	case "FAILED":
		return PayoutDetailStatusFailed, nil
	}
	var t PayoutDetailStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PayoutDetailStatus) Ptr() *PayoutDetailStatus {
	return &p
}

// HATEOAS link for navigating payout resources.
type PayoutLink struct {
	// Relation type of the link.
	Rel *string `json:"rel,omitempty" url:"rel,omitempty"`
	// URL of the related resource.
	Href *string `json:"href,omitempty" url:"href,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutLink) GetRel() *string {
	if p == nil {
		return nil
	}
	return p.Rel
}

func (p *PayoutLink) GetHref() *string {
	if p == nil {
		return nil
	}
	return p.Href
}

func (p *PayoutLink) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutLink) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutLink
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutLink(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutLink) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Monetary amount with currency (no min/max constraints). Used for fees, tax, and balance values.
type SimpleAmount struct {
	// Amount in the smallest currency unit (paisa for INR).
	Value int `json:"value" url:"value"`
	// Three-letter ISO 4217 currency code.
	Currency string `json:"currency" url:"currency"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SimpleAmount) GetValue() int {
	if s == nil {
		return 0
	}
	return s.Value
}

func (s *SimpleAmount) GetCurrency() string {
	if s == nil {
		return ""
	}
	return s.Currency
}

func (s *SimpleAmount) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SimpleAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler SimpleAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SimpleAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SimpleAmount) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Mode of payment for the payout.
type CreatePayoutRequestMode string

const (
	CreatePayoutRequestModeUpi  CreatePayoutRequestMode = "UPI"
	CreatePayoutRequestModeImps CreatePayoutRequestMode = "IMPS"
	CreatePayoutRequestModeNeft CreatePayoutRequestMode = "NEFT"
	CreatePayoutRequestModeRtgs CreatePayoutRequestMode = "RTGS"
)

func NewCreatePayoutRequestModeFromString(s string) (CreatePayoutRequestMode, error) {
	switch s {
	case "UPI":
		return CreatePayoutRequestModeUpi, nil
	case "IMPS":
		return CreatePayoutRequestModeImps, nil
	case "NEFT":
		return CreatePayoutRequestModeNeft, nil
	case "RTGS":
		return CreatePayoutRequestModeRtgs, nil
	}
	var t CreatePayoutRequestMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePayoutRequestMode) Ptr() *CreatePayoutRequestMode {
	return &c
}

type ListPayoutsRequestMode string

const (
	ListPayoutsRequestModeUpi  ListPayoutsRequestMode = "UPI"
	ListPayoutsRequestModeImps ListPayoutsRequestMode = "IMPS"
	ListPayoutsRequestModeNeft ListPayoutsRequestMode = "NEFT"
	ListPayoutsRequestModeRtgs ListPayoutsRequestMode = "RTGS"
)

func NewListPayoutsRequestModeFromString(s string) (ListPayoutsRequestMode, error) {
	switch s {
	case "UPI":
		return ListPayoutsRequestModeUpi, nil
	case "IMPS":
		return ListPayoutsRequestModeImps, nil
	case "NEFT":
		return ListPayoutsRequestModeNeft, nil
	case "RTGS":
		return ListPayoutsRequestModeRtgs, nil
	}
	var t ListPayoutsRequestMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListPayoutsRequestMode) Ptr() *ListPayoutsRequestMode {
	return &l
}

type ListPayoutsRequestStatus string

const (
	ListPayoutsRequestStatusScheduled  ListPayoutsRequestStatus = "SCHEDULED"
	ListPayoutsRequestStatusPending    ListPayoutsRequestStatus = "PENDING"
	ListPayoutsRequestStatusProcessing ListPayoutsRequestStatus = "PROCESSING"
	ListPayoutsRequestStatusProcessed  ListPayoutsRequestStatus = "PROCESSED"
	ListPayoutsRequestStatusSuccess    ListPayoutsRequestStatus = "SUCCESS"
	ListPayoutsRequestStatusFailed     ListPayoutsRequestStatus = "FAILED"
)

func NewListPayoutsRequestStatusFromString(s string) (ListPayoutsRequestStatus, error) {
	switch s {
	case "SCHEDULED":
		return ListPayoutsRequestStatusScheduled, nil
	case "PENDING":
		return ListPayoutsRequestStatusPending, nil
	case "PROCESSING":
		return ListPayoutsRequestStatusProcessing, nil
	case "PROCESSED":
		return ListPayoutsRequestStatusProcessed, nil
	case "SUCCESS":
		return ListPayoutsRequestStatusSuccess, nil
	case "FAILED":
		return ListPayoutsRequestStatusFailed, nil
	}
	var t ListPayoutsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListPayoutsRequestStatus) Ptr() *ListPayoutsRequestStatus {
	return &l
}
