// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CancelSettlementRequest struct {
}

type ReleaseSettlementRequest struct {
	// The amount to release from the held settlement.
	ReleaseAmount *ReleaseSettlementRequestReleaseAmount `json:"release_amount,omitempty" url:"-"`
}

// Payment details in a split settlement response.
type SplitPaymentObject struct {
	ID                       *string                          `json:"id,omitempty" url:"id,omitempty"`
	MerchantPaymentReference *string                          `json:"merchant_payment_reference,omitempty" url:"merchant_payment_reference,omitempty"`
	Status                   *SplitPaymentObjectStatus        `json:"status,omitempty" url:"status,omitempty"`
	PaymentAmount            *SplitPaymentObjectPaymentAmount `json:"payment_amount,omitempty" url:"payment_amount,omitempty"`
	PaymentMethod            *SplitPaymentObjectPaymentMethod `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	PaymentOption            *SplitPaymentObjectPaymentOption `json:"payment_option,omitempty" url:"payment_option,omitempty"`
	AcquirerData             *SplitPaymentObjectAcquirerData  `json:"acquirer_data,omitempty" url:"acquirer_data,omitempty"`
	// Capture details. Present only for pre-authorized orders.
	CaptureData []*SplitPaymentObjectCaptureDataItem `json:"capture_data,omitempty" url:"capture_data,omitempty"`
	// Additional details related to the payment.
	AdditionalDetail *SplitPaymentObjectAdditionalDetail `json:"additional_detail,omitempty" url:"additional_detail,omitempty"`
	CreatedAt        *time.Time                          `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt        *time.Time                          `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObject) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SplitPaymentObject) GetMerchantPaymentReference() *string {
	if s == nil {
		return nil
	}
	return s.MerchantPaymentReference
}

func (s *SplitPaymentObject) GetStatus() *SplitPaymentObjectStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SplitPaymentObject) GetPaymentAmount() *SplitPaymentObjectPaymentAmount {
	if s == nil {
		return nil
	}
	return s.PaymentAmount
}

func (s *SplitPaymentObject) GetPaymentMethod() *SplitPaymentObjectPaymentMethod {
	if s == nil {
		return nil
	}
	return s.PaymentMethod
}

func (s *SplitPaymentObject) GetPaymentOption() *SplitPaymentObjectPaymentOption {
	if s == nil {
		return nil
	}
	return s.PaymentOption
}

func (s *SplitPaymentObject) GetAcquirerData() *SplitPaymentObjectAcquirerData {
	if s == nil {
		return nil
	}
	return s.AcquirerData
}

func (s *SplitPaymentObject) GetCaptureData() []*SplitPaymentObjectCaptureDataItem {
	if s == nil {
		return nil
	}
	return s.CaptureData
}

func (s *SplitPaymentObject) GetAdditionalDetail() *SplitPaymentObjectAdditionalDetail {
	if s == nil {
		return nil
	}
	return s.AdditionalDetail
}

func (s *SplitPaymentObject) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SplitPaymentObject) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *SplitPaymentObject) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObject) UnmarshalJSON(data []byte) error {
	type embed SplitPaymentObject
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SplitPaymentObject(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	s.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObject) MarshalJSON() ([]byte, error) {
	type embed SplitPaymentObject
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*s),
		CreatedAt: core.NewOptionalDateTime(s.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(s.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *SplitPaymentObject) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectAcquirerData struct {
	ApprovalCode      *string `json:"approval_code,omitempty" url:"approval_code,omitempty"`
	AcquirerReference *string `json:"acquirer_reference,omitempty" url:"acquirer_reference,omitempty"`
	Rrn               *string `json:"rrn,omitempty" url:"rrn,omitempty"`
	IsAggregator      *bool   `json:"is_aggregator,omitempty" url:"is_aggregator,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectAcquirerData) GetApprovalCode() *string {
	if s == nil {
		return nil
	}
	return s.ApprovalCode
}

func (s *SplitPaymentObjectAcquirerData) GetAcquirerReference() *string {
	if s == nil {
		return nil
	}
	return s.AcquirerReference
}

func (s *SplitPaymentObjectAcquirerData) GetRrn() *string {
	if s == nil {
		return nil
	}
	return s.Rrn
}

func (s *SplitPaymentObjectAcquirerData) GetIsAggregator() *bool {
	if s == nil {
		return nil
	}
	return s.IsAggregator
}

func (s *SplitPaymentObjectAcquirerData) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectAcquirerData) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitPaymentObjectAcquirerData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitPaymentObjectAcquirerData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectAcquirerData) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Additional details related to the payment.
type SplitPaymentObjectAdditionalDetail struct {
	// IP address of the merchant.
	SourceIP *string `json:"source_ip,omitempty" url:"source_ip,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectAdditionalDetail) GetSourceIP() *string {
	if s == nil {
		return nil
	}
	return s.SourceIP
}

func (s *SplitPaymentObjectAdditionalDetail) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectAdditionalDetail) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitPaymentObjectAdditionalDetail
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitPaymentObjectAdditionalDetail(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectAdditionalDetail) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectCaptureDataItem struct {
	MerchantCaptureReference *string                                         `json:"merchant_capture_reference,omitempty" url:"merchant_capture_reference,omitempty"`
	CaptureAmount            *SplitPaymentObjectCaptureDataItemCaptureAmount `json:"capture_amount,omitempty" url:"capture_amount,omitempty"`
	CreatedAt                *time.Time                                      `json:"created_at,omitempty" url:"created_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectCaptureDataItem) GetMerchantCaptureReference() *string {
	if s == nil {
		return nil
	}
	return s.MerchantCaptureReference
}

func (s *SplitPaymentObjectCaptureDataItem) GetCaptureAmount() *SplitPaymentObjectCaptureDataItemCaptureAmount {
	if s == nil {
		return nil
	}
	return s.CaptureAmount
}

func (s *SplitPaymentObjectCaptureDataItem) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SplitPaymentObjectCaptureDataItem) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectCaptureDataItem) UnmarshalJSON(data []byte) error {
	type embed SplitPaymentObjectCaptureDataItem
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SplitPaymentObjectCaptureDataItem(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectCaptureDataItem) MarshalJSON() ([]byte, error) {
	type embed SplitPaymentObjectCaptureDataItem
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
	}{
		embed:     embed(*s),
		CreatedAt: core.NewOptionalDateTime(s.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *SplitPaymentObjectCaptureDataItem) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectCaptureDataItemCaptureAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectCaptureDataItemCaptureAmount) GetValue() *int {
	if s == nil {
		return nil
	}
	return s.Value
}

func (s *SplitPaymentObjectCaptureDataItemCaptureAmount) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *SplitPaymentObjectCaptureDataItemCaptureAmount) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectCaptureDataItemCaptureAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitPaymentObjectCaptureDataItemCaptureAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitPaymentObjectCaptureDataItemCaptureAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectCaptureDataItemCaptureAmount) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectPaymentAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectPaymentAmount) GetValue() *int {
	if s == nil {
		return nil
	}
	return s.Value
}

func (s *SplitPaymentObjectPaymentAmount) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *SplitPaymentObjectPaymentAmount) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectPaymentAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitPaymentObjectPaymentAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitPaymentObjectPaymentAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectPaymentAmount) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectPaymentMethod string

const (
	SplitPaymentObjectPaymentMethodCard       SplitPaymentObjectPaymentMethod = "CARD"
	SplitPaymentObjectPaymentMethodUpi        SplitPaymentObjectPaymentMethod = "UPI"
	SplitPaymentObjectPaymentMethodPoints     SplitPaymentObjectPaymentMethod = "POINTS"
	SplitPaymentObjectPaymentMethodNetbanking SplitPaymentObjectPaymentMethod = "NETBANKING"
	SplitPaymentObjectPaymentMethodWallet     SplitPaymentObjectPaymentMethod = "WALLET"
)

func NewSplitPaymentObjectPaymentMethodFromString(s string) (SplitPaymentObjectPaymentMethod, error) {
	switch s {
	case "CARD":
		return SplitPaymentObjectPaymentMethodCard, nil
	case "UPI":
		return SplitPaymentObjectPaymentMethodUpi, nil
	case "POINTS":
		return SplitPaymentObjectPaymentMethodPoints, nil
	case "NETBANKING":
		return SplitPaymentObjectPaymentMethodNetbanking, nil
	case "WALLET":
		return SplitPaymentObjectPaymentMethodWallet, nil
	}
	var t SplitPaymentObjectPaymentMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitPaymentObjectPaymentMethod) Ptr() *SplitPaymentObjectPaymentMethod {
	return &s
}

type SplitPaymentObjectPaymentOption struct {
	CardData *SplitPaymentObjectPaymentOptionCardData `json:"card_data,omitempty" url:"card_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectPaymentOption) GetCardData() *SplitPaymentObjectPaymentOptionCardData {
	if s == nil {
		return nil
	}
	return s.CardData
}

func (s *SplitPaymentObjectPaymentOption) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectPaymentOption) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitPaymentObjectPaymentOption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitPaymentObjectPaymentOption(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectPaymentOption) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectPaymentOptionCardData struct {
	CardType    *SplitPaymentObjectPaymentOptionCardDataCardType `json:"card_type,omitempty" url:"card_type,omitempty"`
	NetworkName *string                                          `json:"network_name,omitempty" url:"network_name,omitempty"`
	IssuerName  *string                                          `json:"issuer_name,omitempty" url:"issuer_name,omitempty"`
	// Card product name.
	ProductName         *string                                              `json:"product_name,omitempty" url:"product_name,omitempty"`
	CardCategory        *string                                              `json:"card_category,omitempty" url:"card_category,omitempty"`
	CountryCode         *string                                              `json:"country_code,omitempty" url:"country_code,omitempty"`
	TokenTxnType        *SplitPaymentObjectPaymentOptionCardDataTokenTxnType `json:"token_txn_type,omitempty" url:"token_txn_type,omitempty"`
	Last4Digit          *string                                              `json:"last4_digit,omitempty" url:"last4_digit,omitempty"`
	Save                *bool                                                `json:"save,omitempty" url:"save,omitempty"`
	IsNativeOtpEligible *bool                                                `json:"is_native_otp_eligible,omitempty" url:"is_native_otp_eligible,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetCardType() *SplitPaymentObjectPaymentOptionCardDataCardType {
	if s == nil {
		return nil
	}
	return s.CardType
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetNetworkName() *string {
	if s == nil {
		return nil
	}
	return s.NetworkName
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetIssuerName() *string {
	if s == nil {
		return nil
	}
	return s.IssuerName
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetProductName() *string {
	if s == nil {
		return nil
	}
	return s.ProductName
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetCardCategory() *string {
	if s == nil {
		return nil
	}
	return s.CardCategory
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetCountryCode() *string {
	if s == nil {
		return nil
	}
	return s.CountryCode
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetTokenTxnType() *SplitPaymentObjectPaymentOptionCardDataTokenTxnType {
	if s == nil {
		return nil
	}
	return s.TokenTxnType
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetLast4Digit() *string {
	if s == nil {
		return nil
	}
	return s.Last4Digit
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetSave() *bool {
	if s == nil {
		return nil
	}
	return s.Save
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetIsNativeOtpEligible() *bool {
	if s == nil {
		return nil
	}
	return s.IsNativeOtpEligible
}

func (s *SplitPaymentObjectPaymentOptionCardData) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitPaymentObjectPaymentOptionCardData) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitPaymentObjectPaymentOptionCardData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitPaymentObjectPaymentOptionCardData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitPaymentObjectPaymentOptionCardData) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitPaymentObjectPaymentOptionCardDataCardType string

const (
	SplitPaymentObjectPaymentOptionCardDataCardTypeDebit  SplitPaymentObjectPaymentOptionCardDataCardType = "DEBIT"
	SplitPaymentObjectPaymentOptionCardDataCardTypeCredit SplitPaymentObjectPaymentOptionCardDataCardType = "CREDIT"
)

func NewSplitPaymentObjectPaymentOptionCardDataCardTypeFromString(s string) (SplitPaymentObjectPaymentOptionCardDataCardType, error) {
	switch s {
	case "DEBIT":
		return SplitPaymentObjectPaymentOptionCardDataCardTypeDebit, nil
	case "CREDIT":
		return SplitPaymentObjectPaymentOptionCardDataCardTypeCredit, nil
	}
	var t SplitPaymentObjectPaymentOptionCardDataCardType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitPaymentObjectPaymentOptionCardDataCardType) Ptr() *SplitPaymentObjectPaymentOptionCardDataCardType {
	return &s
}

type SplitPaymentObjectPaymentOptionCardDataTokenTxnType string

const (
	SplitPaymentObjectPaymentOptionCardDataTokenTxnTypeAltToken     SplitPaymentObjectPaymentOptionCardDataTokenTxnType = "ALT_TOKEN"
	SplitPaymentObjectPaymentOptionCardDataTokenTxnTypeNetworkToken SplitPaymentObjectPaymentOptionCardDataTokenTxnType = "NETWORK_TOKEN"
	SplitPaymentObjectPaymentOptionCardDataTokenTxnTypeIssuerToken  SplitPaymentObjectPaymentOptionCardDataTokenTxnType = "ISSUER_TOKEN"
)

func NewSplitPaymentObjectPaymentOptionCardDataTokenTxnTypeFromString(s string) (SplitPaymentObjectPaymentOptionCardDataTokenTxnType, error) {
	switch s {
	case "ALT_TOKEN":
		return SplitPaymentObjectPaymentOptionCardDataTokenTxnTypeAltToken, nil
	case "NETWORK_TOKEN":
		return SplitPaymentObjectPaymentOptionCardDataTokenTxnTypeNetworkToken, nil
	case "ISSUER_TOKEN":
		return SplitPaymentObjectPaymentOptionCardDataTokenTxnTypeIssuerToken, nil
	}
	var t SplitPaymentObjectPaymentOptionCardDataTokenTxnType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitPaymentObjectPaymentOptionCardDataTokenTxnType) Ptr() *SplitPaymentObjectPaymentOptionCardDataTokenTxnType {
	return &s
}

type SplitPaymentObjectStatus string

const (
	SplitPaymentObjectStatusPending    SplitPaymentObjectStatus = "PENDING"
	SplitPaymentObjectStatusAuthorized SplitPaymentObjectStatus = "AUTHORIZED"
	SplitPaymentObjectStatusCancelled  SplitPaymentObjectStatus = "CANCELLED"
	SplitPaymentObjectStatusProcessed  SplitPaymentObjectStatus = "PROCESSED"
	SplitPaymentObjectStatusFailed     SplitPaymentObjectStatus = "FAILED"
)

func NewSplitPaymentObjectStatusFromString(s string) (SplitPaymentObjectStatus, error) {
	switch s {
	case "PENDING":
		return SplitPaymentObjectStatusPending, nil
	case "AUTHORIZED":
		return SplitPaymentObjectStatusAuthorized, nil
	case "CANCELLED":
		return SplitPaymentObjectStatusCancelled, nil
	case "PROCESSED":
		return SplitPaymentObjectStatusProcessed, nil
	case "FAILED":
		return SplitPaymentObjectStatusFailed, nil
	}
	var t SplitPaymentObjectStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitPaymentObjectStatus) Ptr() *SplitPaymentObjectStatus {
	return &s
}

// Individual split settlement detail.
type SplitSettlementDetail struct {
	// Unique identifier of the partner merchant.
	SplitMerchantID *string `json:"split_merchant_id,omitempty" url:"split_merchant_id,omitempty"`
	// Unique identifier of the split settlement.
	SplitSettlementID *string                      `json:"split_settlement_id,omitempty" url:"split_settlement_id,omitempty"`
	Amount            *SplitSettlementDetailAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Whether the settlement is on hold.
	OnHold *bool `json:"on_hold,omitempty" url:"on_hold,omitempty"`
	// Split settlement status.
	Status    *SplitSettlementDetailStatus `json:"status,omitempty" url:"status,omitempty"`
	UpdatedAt *time.Time                   `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// Release amount (present only when status is RELEASED).
	ReleaseAmount *SplitSettlementDetailReleaseAmount `json:"release_amount,omitempty" url:"release_amount,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementDetail) GetSplitMerchantID() *string {
	if s == nil {
		return nil
	}
	return s.SplitMerchantID
}

func (s *SplitSettlementDetail) GetSplitSettlementID() *string {
	if s == nil {
		return nil
	}
	return s.SplitSettlementID
}

func (s *SplitSettlementDetail) GetAmount() *SplitSettlementDetailAmount {
	if s == nil {
		return nil
	}
	return s.Amount
}

func (s *SplitSettlementDetail) GetOnHold() *bool {
	if s == nil {
		return nil
	}
	return s.OnHold
}

func (s *SplitSettlementDetail) GetStatus() *SplitSettlementDetailStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SplitSettlementDetail) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *SplitSettlementDetail) GetReleaseAmount() *SplitSettlementDetailReleaseAmount {
	if s == nil {
		return nil
	}
	return s.ReleaseAmount
}

func (s *SplitSettlementDetail) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementDetail) UnmarshalJSON(data []byte) error {
	type embed SplitSettlementDetail
	var unmarshaler = struct {
		embed
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SplitSettlementDetail(unmarshaler.embed)
	s.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementDetail) MarshalJSON() ([]byte, error) {
	type embed SplitSettlementDetail
	var marshaler = struct {
		embed
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*s),
		UpdatedAt: core.NewOptionalDateTime(s.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *SplitSettlementDetail) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementDetailAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementDetailAmount) GetValue() *int {
	if s == nil {
		return nil
	}
	return s.Value
}

func (s *SplitSettlementDetailAmount) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *SplitSettlementDetailAmount) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementDetailAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementDetailAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementDetailAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementDetailAmount) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Release amount (present only when status is RELEASED).
type SplitSettlementDetailReleaseAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementDetailReleaseAmount) GetValue() *int {
	if s == nil {
		return nil
	}
	return s.Value
}

func (s *SplitSettlementDetailReleaseAmount) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *SplitSettlementDetailReleaseAmount) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementDetailReleaseAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementDetailReleaseAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementDetailReleaseAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementDetailReleaseAmount) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Split settlement status.
type SplitSettlementDetailStatus string

const (
	SplitSettlementDetailStatusReleased SplitSettlementDetailStatus = "RELEASED"
	SplitSettlementDetailStatusHold     SplitSettlementDetailStatus = "HOLD"
)

func NewSplitSettlementDetailStatusFromString(s string) (SplitSettlementDetailStatus, error) {
	switch s {
	case "RELEASED":
		return SplitSettlementDetailStatusReleased, nil
	case "HOLD":
		return SplitSettlementDetailStatusHold, nil
	}
	var t SplitSettlementDetailStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitSettlementDetailStatus) Ptr() *SplitSettlementDetailStatus {
	return &s
}

// Response returned after release or cancel settlement operations.
type SplitSettlementResponse struct {
	Data *SplitSettlementResponseData `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementResponse) GetData() *SplitSettlementResponseData {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SplitSettlementResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementResponse) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementResponseData struct {
	OrderID                 *string                                                `json:"order_id,omitempty" url:"order_id,omitempty"`
	MerchantOrderReference  *string                                                `json:"merchant_order_reference,omitempty" url:"merchant_order_reference,omitempty"`
	Type                    *SplitSettlementResponseDataType                       `json:"type,omitempty" url:"type,omitempty"`
	Status                  *SplitSettlementResponseDataStatus                     `json:"status,omitempty" url:"status,omitempty"`
	MerchantID              *string                                                `json:"merchant_id,omitempty" url:"merchant_id,omitempty"`
	OrderAmount             *SplitSettlementResponseDataOrderAmount                `json:"order_amount,omitempty" url:"order_amount,omitempty"`
	PreAuth                 *bool                                                  `json:"pre_auth,omitempty" url:"pre_auth,omitempty"`
	AllowedPaymentMethods   []SplitSettlementResponseDataAllowedPaymentMethodsItem `json:"allowed_payment_methods,omitempty" url:"allowed_payment_methods,omitempty"`
	Notes                   *string                                                `json:"notes,omitempty" url:"notes,omitempty"`
	PurchaseDetails         *SplitSettlementResponseDataPurchaseDetails            `json:"purchase_details,omitempty" url:"purchase_details,omitempty"`
	Payments                []*SplitPaymentObject                                  `json:"payments,omitempty" url:"payments,omitempty"`
	CreatedAt               *time.Time                                             `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt               *time.Time                                             `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	IntegrationMode         *SplitSettlementResponseDataIntegrationMode            `json:"integration_mode,omitempty" url:"integration_mode,omitempty"`
	PaymentRetriesRemaining *int                                                   `json:"payment_retries_remaining,omitempty" url:"payment_retries_remaining,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementResponseData) GetOrderID() *string {
	if s == nil {
		return nil
	}
	return s.OrderID
}

func (s *SplitSettlementResponseData) GetMerchantOrderReference() *string {
	if s == nil {
		return nil
	}
	return s.MerchantOrderReference
}

func (s *SplitSettlementResponseData) GetType() *SplitSettlementResponseDataType {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *SplitSettlementResponseData) GetStatus() *SplitSettlementResponseDataStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SplitSettlementResponseData) GetMerchantID() *string {
	if s == nil {
		return nil
	}
	return s.MerchantID
}

func (s *SplitSettlementResponseData) GetOrderAmount() *SplitSettlementResponseDataOrderAmount {
	if s == nil {
		return nil
	}
	return s.OrderAmount
}

func (s *SplitSettlementResponseData) GetPreAuth() *bool {
	if s == nil {
		return nil
	}
	return s.PreAuth
}

func (s *SplitSettlementResponseData) GetAllowedPaymentMethods() []SplitSettlementResponseDataAllowedPaymentMethodsItem {
	if s == nil {
		return nil
	}
	return s.AllowedPaymentMethods
}

func (s *SplitSettlementResponseData) GetNotes() *string {
	if s == nil {
		return nil
	}
	return s.Notes
}

func (s *SplitSettlementResponseData) GetPurchaseDetails() *SplitSettlementResponseDataPurchaseDetails {
	if s == nil {
		return nil
	}
	return s.PurchaseDetails
}

func (s *SplitSettlementResponseData) GetPayments() []*SplitPaymentObject {
	if s == nil {
		return nil
	}
	return s.Payments
}

func (s *SplitSettlementResponseData) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SplitSettlementResponseData) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *SplitSettlementResponseData) GetIntegrationMode() *SplitSettlementResponseDataIntegrationMode {
	if s == nil {
		return nil
	}
	return s.IntegrationMode
}

func (s *SplitSettlementResponseData) GetPaymentRetriesRemaining() *int {
	if s == nil {
		return nil
	}
	return s.PaymentRetriesRemaining
}

func (s *SplitSettlementResponseData) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementResponseData) UnmarshalJSON(data []byte) error {
	type embed SplitSettlementResponseData
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SplitSettlementResponseData(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	s.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementResponseData) MarshalJSON() ([]byte, error) {
	type embed SplitSettlementResponseData
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*s),
		CreatedAt: core.NewOptionalDateTime(s.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(s.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *SplitSettlementResponseData) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementResponseDataAllowedPaymentMethodsItem string

const (
	SplitSettlementResponseDataAllowedPaymentMethodsItemCard       SplitSettlementResponseDataAllowedPaymentMethodsItem = "CARD"
	SplitSettlementResponseDataAllowedPaymentMethodsItemUpi        SplitSettlementResponseDataAllowedPaymentMethodsItem = "UPI"
	SplitSettlementResponseDataAllowedPaymentMethodsItemNetbanking SplitSettlementResponseDataAllowedPaymentMethodsItem = "NETBANKING"
	SplitSettlementResponseDataAllowedPaymentMethodsItemPoints     SplitSettlementResponseDataAllowedPaymentMethodsItem = "POINTS"
	SplitSettlementResponseDataAllowedPaymentMethodsItemWallet     SplitSettlementResponseDataAllowedPaymentMethodsItem = "WALLET"
)

func NewSplitSettlementResponseDataAllowedPaymentMethodsItemFromString(s string) (SplitSettlementResponseDataAllowedPaymentMethodsItem, error) {
	switch s {
	case "CARD":
		return SplitSettlementResponseDataAllowedPaymentMethodsItemCard, nil
	case "UPI":
		return SplitSettlementResponseDataAllowedPaymentMethodsItemUpi, nil
	case "NETBANKING":
		return SplitSettlementResponseDataAllowedPaymentMethodsItemNetbanking, nil
	case "POINTS":
		return SplitSettlementResponseDataAllowedPaymentMethodsItemPoints, nil
	case "WALLET":
		return SplitSettlementResponseDataAllowedPaymentMethodsItemWallet, nil
	}
	var t SplitSettlementResponseDataAllowedPaymentMethodsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitSettlementResponseDataAllowedPaymentMethodsItem) Ptr() *SplitSettlementResponseDataAllowedPaymentMethodsItem {
	return &s
}

type SplitSettlementResponseDataIntegrationMode string

const (
	SplitSettlementResponseDataIntegrationModeSeamless SplitSettlementResponseDataIntegrationMode = "SEAMLESS"
	SplitSettlementResponseDataIntegrationModeRedirect SplitSettlementResponseDataIntegrationMode = "REDIRECT"
)

func NewSplitSettlementResponseDataIntegrationModeFromString(s string) (SplitSettlementResponseDataIntegrationMode, error) {
	switch s {
	case "SEAMLESS":
		return SplitSettlementResponseDataIntegrationModeSeamless, nil
	case "REDIRECT":
		return SplitSettlementResponseDataIntegrationModeRedirect, nil
	}
	var t SplitSettlementResponseDataIntegrationMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitSettlementResponseDataIntegrationMode) Ptr() *SplitSettlementResponseDataIntegrationMode {
	return &s
}

type SplitSettlementResponseDataOrderAmount struct {
	Value    *int    `json:"value,omitempty" url:"value,omitempty"`
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementResponseDataOrderAmount) GetValue() *int {
	if s == nil {
		return nil
	}
	return s.Value
}

func (s *SplitSettlementResponseDataOrderAmount) GetCurrency() *string {
	if s == nil {
		return nil
	}
	return s.Currency
}

func (s *SplitSettlementResponseDataOrderAmount) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementResponseDataOrderAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementResponseDataOrderAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementResponseDataOrderAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementResponseDataOrderAmount) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementResponseDataPurchaseDetails struct {
	Customer         *SplitSettlementResponseDataPurchaseDetailsCustomer  `json:"customer,omitempty" url:"customer,omitempty"`
	MerchantMetadata *MerchantMetadata                                    `json:"merchant_metadata,omitempty" url:"merchant_metadata,omitempty"`
	SplitInfo        *SplitSettlementResponseDataPurchaseDetailsSplitInfo `json:"split_info,omitempty" url:"split_info,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementResponseDataPurchaseDetails) GetCustomer() *SplitSettlementResponseDataPurchaseDetailsCustomer {
	if s == nil {
		return nil
	}
	return s.Customer
}

func (s *SplitSettlementResponseDataPurchaseDetails) GetMerchantMetadata() *MerchantMetadata {
	if s == nil {
		return nil
	}
	return s.MerchantMetadata
}

func (s *SplitSettlementResponseDataPurchaseDetails) GetSplitInfo() *SplitSettlementResponseDataPurchaseDetailsSplitInfo {
	if s == nil {
		return nil
	}
	return s.SplitInfo
}

func (s *SplitSettlementResponseDataPurchaseDetails) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementResponseDataPurchaseDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementResponseDataPurchaseDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementResponseDataPurchaseDetails(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementResponseDataPurchaseDetails) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementResponseDataPurchaseDetailsCustomer struct {
	EmailID                      *string  `json:"email_id,omitempty" url:"email_id,omitempty"`
	FirstName                    *string  `json:"first_name,omitempty" url:"first_name,omitempty"`
	LastName                     *string  `json:"last_name,omitempty" url:"last_name,omitempty"`
	CustomerID                   *string  `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	CountryCode                  *string  `json:"country_code,omitempty" url:"country_code,omitempty"`
	MobileNumber                 *string  `json:"mobile_number,omitempty" url:"mobile_number,omitempty"`
	BillingAddress               *Address `json:"billing_address,omitempty" url:"billing_address,omitempty"`
	ShippingAddress              *Address `json:"shipping_address,omitempty" url:"shipping_address,omitempty"`
	IsEditCustomerDetailsAllowed *bool    `json:"is_edit_customer_details_allowed,omitempty" url:"is_edit_customer_details_allowed,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetEmailID() *string {
	if s == nil {
		return nil
	}
	return s.EmailID
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetFirstName() *string {
	if s == nil {
		return nil
	}
	return s.FirstName
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetLastName() *string {
	if s == nil {
		return nil
	}
	return s.LastName
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetCountryCode() *string {
	if s == nil {
		return nil
	}
	return s.CountryCode
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetMobileNumber() *string {
	if s == nil {
		return nil
	}
	return s.MobileNumber
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetBillingAddress() *Address {
	if s == nil {
		return nil
	}
	return s.BillingAddress
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetShippingAddress() *Address {
	if s == nil {
		return nil
	}
	return s.ShippingAddress
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetIsEditCustomerDetailsAllowed() *bool {
	if s == nil {
		return nil
	}
	return s.IsEditCustomerDetailsAllowed
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementResponseDataPurchaseDetailsCustomer
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementResponseDataPurchaseDetailsCustomer(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementResponseDataPurchaseDetailsCustomer) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementResponseDataPurchaseDetailsSplitInfo struct {
	SplitType    *string                  `json:"split_type,omitempty" url:"split_type,omitempty"`
	SplitDetails []*SplitSettlementDetail `json:"split_details,omitempty" url:"split_details,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SplitSettlementResponseDataPurchaseDetailsSplitInfo) GetSplitType() *string {
	if s == nil {
		return nil
	}
	return s.SplitType
}

func (s *SplitSettlementResponseDataPurchaseDetailsSplitInfo) GetSplitDetails() []*SplitSettlementDetail {
	if s == nil {
		return nil
	}
	return s.SplitDetails
}

func (s *SplitSettlementResponseDataPurchaseDetailsSplitInfo) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SplitSettlementResponseDataPurchaseDetailsSplitInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SplitSettlementResponseDataPurchaseDetailsSplitInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SplitSettlementResponseDataPurchaseDetailsSplitInfo(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SplitSettlementResponseDataPurchaseDetailsSplitInfo) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SplitSettlementResponseDataStatus string

const (
	SplitSettlementResponseDataStatusCreated           SplitSettlementResponseDataStatus = "CREATED"
	SplitSettlementResponseDataStatusPending           SplitSettlementResponseDataStatus = "PENDING"
	SplitSettlementResponseDataStatusProcessed         SplitSettlementResponseDataStatus = "PROCESSED"
	SplitSettlementResponseDataStatusAuthorized        SplitSettlementResponseDataStatus = "AUTHORIZED"
	SplitSettlementResponseDataStatusCancelled         SplitSettlementResponseDataStatus = "CANCELLED"
	SplitSettlementResponseDataStatusAttempted         SplitSettlementResponseDataStatus = "ATTEMPTED"
	SplitSettlementResponseDataStatusFailed            SplitSettlementResponseDataStatus = "FAILED"
	SplitSettlementResponseDataStatusFullyRefunded     SplitSettlementResponseDataStatus = "FULLY_REFUNDED"
	SplitSettlementResponseDataStatusPartiallyRefunded SplitSettlementResponseDataStatus = "PARTIALLY_REFUNDED"
)

func NewSplitSettlementResponseDataStatusFromString(s string) (SplitSettlementResponseDataStatus, error) {
	switch s {
	case "CREATED":
		return SplitSettlementResponseDataStatusCreated, nil
	case "PENDING":
		return SplitSettlementResponseDataStatusPending, nil
	case "PROCESSED":
		return SplitSettlementResponseDataStatusProcessed, nil
	case "AUTHORIZED":
		return SplitSettlementResponseDataStatusAuthorized, nil
	case "CANCELLED":
		return SplitSettlementResponseDataStatusCancelled, nil
	case "ATTEMPTED":
		return SplitSettlementResponseDataStatusAttempted, nil
	case "FAILED":
		return SplitSettlementResponseDataStatusFailed, nil
	case "FULLY_REFUNDED":
		return SplitSettlementResponseDataStatusFullyRefunded, nil
	case "PARTIALLY_REFUNDED":
		return SplitSettlementResponseDataStatusPartiallyRefunded, nil
	}
	var t SplitSettlementResponseDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitSettlementResponseDataStatus) Ptr() *SplitSettlementResponseDataStatus {
	return &s
}

type SplitSettlementResponseDataType string

const (
	SplitSettlementResponseDataTypeCharge SplitSettlementResponseDataType = "CHARGE"
	SplitSettlementResponseDataTypeRefund SplitSettlementResponseDataType = "REFUND"
)

func NewSplitSettlementResponseDataTypeFromString(s string) (SplitSettlementResponseDataType, error) {
	switch s {
	case "CHARGE":
		return SplitSettlementResponseDataTypeCharge, nil
	case "REFUND":
		return SplitSettlementResponseDataTypeRefund, nil
	}
	var t SplitSettlementResponseDataType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SplitSettlementResponseDataType) Ptr() *SplitSettlementResponseDataType {
	return &s
}

// The amount to release from the held settlement.
type ReleaseSettlementRequestReleaseAmount struct {
	// Amount in smallest currency unit (paisa).
	Value int `json:"value" url:"value"`
	// Three-letter ISO 4217 currency code.
	Currency string `json:"currency" url:"currency"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (r *ReleaseSettlementRequestReleaseAmount) GetValue() int {
	if r == nil {
		return 0
	}
	return r.Value
}

func (r *ReleaseSettlementRequestReleaseAmount) GetCurrency() string {
	if r == nil {
		return ""
	}
	return r.Currency
}

func (r *ReleaseSettlementRequestReleaseAmount) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ReleaseSettlementRequestReleaseAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler ReleaseSettlementRequestReleaseAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReleaseSettlementRequestReleaseAmount(value)

	extraProperties, err := core.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties

	r._rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReleaseSettlementRequestReleaseAmount) String() string {
	if len(r._rawJSON) > 0 {
		if value, err := core.StringifyJSON(r._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
