// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CreateDebitRequest struct {
	// Presentation ID from Pine Labs.
	PresentationID *string `json:"presentation_id,omitempty" url:"-"`
	// Merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"-"`
	// Set to true to control retry process yourself.
	IsMerchantRetry *string `json:"is_merchant_retry,omitempty" url:"-"`
}

type MerchantRetryRequest struct {
	// Presentation ID from Pine Labs.
	PresentationID *string `json:"presentation_id,omitempty" url:"-"`
	// Merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"-"`
}

type CreatePresentationRequest struct {
	// The ISO 8601 UTC Timestamp when the payment is due.
	DueDate *time.Time          `json:"due_date,omitempty" url:"-"`
	Amount  *SubscriptionAmount `json:"amount,omitempty" url:"-"`
	// Unique identifier of the merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"-"`
}

func (c *CreatePresentationRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePresentationRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePresentationRequest(body)
	return nil
}

func (c *CreatePresentationRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePresentationRequest
	var marshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed:   embed(*c),
		DueDate: core.NewOptionalDateTime(c.DueDate),
	}
	return json.Marshal(marshaler)
}

type DeletePresentationRequest struct {
}

type GetPresentationByIDRequest struct {
}

type GetPresentationByMerchantReferenceRequest struct {
}

type ListPresentationsBySubscriptionRequest struct {
	// Number of items per page.
	Size *string `json:"-" url:"size,omitempty"`
	// Page number.
	Page *string `json:"-" url:"page,omitempty"`
	// Sort field and direction.
	Sort *string `json:"-" url:"sort,omitempty"`
}

type SubscriptionNotificationRequest struct {
	// Unique identifier for the subscription.
	SubscriptionID string `json:"subscription_id" url:"-"`
	// The ISO 8601 UTC Timestamp when the payment is due.
	DueDate time.Time           `json:"due_date" url:"-"`
	Amount  *SubscriptionAmount `json:"amount,omitempty" url:"-"`
	// **Idempotency Key.** Unique identifier of the merchant presentation reference. Duplicate requests with the same `merchant_presentation_reference` will return the existing presentation instead of creating a new one.
	MerchantPresentationReference string `json:"merchant_presentation_reference" url:"-"`
	// Indicates whether the merchant controls the retry process.
	IsMerchantRetry *bool `json:"is_merchant_retry,omitempty" url:"-"`
}

func (s *SubscriptionNotificationRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscriptionNotificationRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SubscriptionNotificationRequest(body)
	return nil
}

func (s *SubscriptionNotificationRequest) MarshalJSON() ([]byte, error) {
	type embed SubscriptionNotificationRequest
	var marshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date"`
	}{
		embed:   embed(*s),
		DueDate: core.NewDateTime(s.DueDate),
	}
	return json.Marshal(marshaler)
}

// Response returned after creating a debit.
type CreateDebitResponse struct {
	// Unique identifier for the subscription.
	SubscriptionID *string `json:"subscription_id,omitempty" url:"subscription_id,omitempty"`
	// Unique identifier for the presentation.
	PresentationID *string `json:"presentation_id,omitempty" url:"presentation_id,omitempty"`
	// The ISO 8601 UTC Timestamp when the payment is due.
	DueDate *time.Time          `json:"due_date,omitempty" url:"due_date,omitempty"`
	Amount  *SubscriptionAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Unique identifier of the merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"merchant_presentation_reference,omitempty"`
	// Debit status.
	// - CREATED: Presentation request successfully received.
	// - PENDING: Pre-debit notification initiated.
	// - PAUSED: Subscription is paused.
	// - CANCELLED: Subscription is cancelled.
	// - FAILED: Pre-debit notification or customer debit fails (up to 3 retries).
	// - COMPLETED: Debit is successful.
	Status *CreateDebitResponseStatus `json:"status,omitempty" url:"status,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateDebitResponse) GetSubscriptionID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionID
}

func (c *CreateDebitResponse) GetPresentationID() *string {
	if c == nil {
		return nil
	}
	return c.PresentationID
}

func (c *CreateDebitResponse) GetDueDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.DueDate
}

func (c *CreateDebitResponse) GetAmount() *SubscriptionAmount {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CreateDebitResponse) GetMerchantPresentationReference() *string {
	if c == nil {
		return nil
	}
	return c.MerchantPresentationReference
}

func (c *CreateDebitResponse) GetStatus() *CreateDebitResponseStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreateDebitResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDebitResponse) UnmarshalJSON(data []byte) error {
	type embed CreateDebitResponse
	var unmarshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateDebitResponse(unmarshaler.embed)
	c.DueDate = unmarshaler.DueDate.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDebitResponse) MarshalJSON() ([]byte, error) {
	type embed CreateDebitResponse
	var marshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed:   embed(*c),
		DueDate: core.NewOptionalDateTime(c.DueDate),
	}
	return json.Marshal(marshaler)
}

func (c *CreateDebitResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Debit status.
// - CREATED: Presentation request successfully received.
// - PENDING: Pre-debit notification initiated.
// - PAUSED: Subscription is paused.
// - CANCELLED: Subscription is cancelled.
// - FAILED: Pre-debit notification or customer debit fails (up to 3 retries).
// - COMPLETED: Debit is successful.
type CreateDebitResponseStatus string

const (
	CreateDebitResponseStatusCreated   CreateDebitResponseStatus = "CREATED"
	CreateDebitResponseStatusPending   CreateDebitResponseStatus = "PENDING"
	CreateDebitResponseStatusPaused    CreateDebitResponseStatus = "PAUSED"
	CreateDebitResponseStatusCancelled CreateDebitResponseStatus = "CANCELLED"
	CreateDebitResponseStatusFailed    CreateDebitResponseStatus = "FAILED"
	CreateDebitResponseStatusCompleted CreateDebitResponseStatus = "COMPLETED"
)

func NewCreateDebitResponseStatusFromString(s string) (CreateDebitResponseStatus, error) {
	switch s {
	case "CREATED":
		return CreateDebitResponseStatusCreated, nil
	case "PENDING":
		return CreateDebitResponseStatusPending, nil
	case "PAUSED":
		return CreateDebitResponseStatusPaused, nil
	case "CANCELLED":
		return CreateDebitResponseStatusCancelled, nil
	case "FAILED":
		return CreateDebitResponseStatusFailed, nil
	case "COMPLETED":
		return CreateDebitResponseStatusCompleted, nil
	}
	var t CreateDebitResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateDebitResponseStatus) Ptr() *CreateDebitResponseStatus {
	return &c
}

// Response returned after creating a presentation.
type CreatePresentationResponse struct {
	// Unique identifier for the subscription.
	SubscriptionID *string `json:"subscription_id,omitempty" url:"subscription_id,omitempty"`
	// Unique identifier for the presentation.
	PresentationID *string `json:"presentation_id,omitempty" url:"presentation_id,omitempty"`
	// The ISO 8601 UTC Timestamp when the payment is due.
	DueDate *time.Time          `json:"due_date,omitempty" url:"due_date,omitempty"`
	Amount  *SubscriptionAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Presentation status.
	// - CREATED: Presentation request created successfully.
	// - PENDING: Request sent to bank, awaiting response.
	// - COMPLETED: Successfully processed.
	// - FAILED: Request failed at bank's end.
	// - CANCELLED: Presentation request cancelled.
	// - PAUSED: Subscription is currently paused.
	// - PARTIALLY_REFUNDED: Partial refund issued.
	// - REFUNDED: Full refund issued.
	Status *CreatePresentationResponseStatus `json:"status,omitempty" url:"status,omitempty"`
	// Unique identifier of the merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"merchant_presentation_reference,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreatePresentationResponse) GetSubscriptionID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionID
}

func (c *CreatePresentationResponse) GetPresentationID() *string {
	if c == nil {
		return nil
	}
	return c.PresentationID
}

func (c *CreatePresentationResponse) GetDueDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.DueDate
}

func (c *CreatePresentationResponse) GetAmount() *SubscriptionAmount {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CreatePresentationResponse) GetStatus() *CreatePresentationResponseStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreatePresentationResponse) GetMerchantPresentationReference() *string {
	if c == nil {
		return nil
	}
	return c.MerchantPresentationReference
}

func (c *CreatePresentationResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreatePresentationResponse) UnmarshalJSON(data []byte) error {
	type embed CreatePresentationResponse
	var unmarshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreatePresentationResponse(unmarshaler.embed)
	c.DueDate = unmarshaler.DueDate.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePresentationResponse) MarshalJSON() ([]byte, error) {
	type embed CreatePresentationResponse
	var marshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed:   embed(*c),
		DueDate: core.NewOptionalDateTime(c.DueDate),
	}
	return json.Marshal(marshaler)
}

func (c *CreatePresentationResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Presentation status.
// - CREATED: Presentation request created successfully.
// - PENDING: Request sent to bank, awaiting response.
// - COMPLETED: Successfully processed.
// - FAILED: Request failed at bank's end.
// - CANCELLED: Presentation request cancelled.
// - PAUSED: Subscription is currently paused.
// - PARTIALLY_REFUNDED: Partial refund issued.
// - REFUNDED: Full refund issued.
type CreatePresentationResponseStatus string

const (
	CreatePresentationResponseStatusCreated           CreatePresentationResponseStatus = "CREATED"
	CreatePresentationResponseStatusPending           CreatePresentationResponseStatus = "PENDING"
	CreatePresentationResponseStatusCompleted         CreatePresentationResponseStatus = "COMPLETED"
	CreatePresentationResponseStatusFailed            CreatePresentationResponseStatus = "FAILED"
	CreatePresentationResponseStatusCancelled         CreatePresentationResponseStatus = "CANCELLED"
	CreatePresentationResponseStatusPaused            CreatePresentationResponseStatus = "PAUSED"
	CreatePresentationResponseStatusPartiallyRefunded CreatePresentationResponseStatus = "PARTIALLY_REFUNDED"
	CreatePresentationResponseStatusRefunded          CreatePresentationResponseStatus = "REFUNDED"
)

func NewCreatePresentationResponseStatusFromString(s string) (CreatePresentationResponseStatus, error) {
	switch s {
	case "CREATED":
		return CreatePresentationResponseStatusCreated, nil
	case "PENDING":
		return CreatePresentationResponseStatusPending, nil
	case "COMPLETED":
		return CreatePresentationResponseStatusCompleted, nil
	case "FAILED":
		return CreatePresentationResponseStatusFailed, nil
	case "CANCELLED":
		return CreatePresentationResponseStatusCancelled, nil
	case "PAUSED":
		return CreatePresentationResponseStatusPaused, nil
	case "PARTIALLY_REFUNDED":
		return CreatePresentationResponseStatusPartiallyRefunded, nil
	case "REFUNDED":
		return CreatePresentationResponseStatusRefunded, nil
	}
	var t CreatePresentationResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePresentationResponseStatus) Ptr() *CreatePresentationResponseStatus {
	return &c
}

// Response returned when listing presentations by subscription ID.
type ListPresentationsResponse struct {
	Links *PaginationLinks `json:"links,omitempty" url:"links,omitempty"`
	Page  *PageInfo        `json:"page,omitempty" url:"page,omitempty"`
	// List of presentation records.
	Presentations []*PresentationDetail `json:"presentations,omitempty" url:"presentations,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (l *ListPresentationsResponse) GetLinks() *PaginationLinks {
	if l == nil {
		return nil
	}
	return l.Links
}

func (l *ListPresentationsResponse) GetPage() *PageInfo {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListPresentationsResponse) GetPresentations() []*PresentationDetail {
	if l == nil {
		return nil
	}
	return l.Presentations
}

func (l *ListPresentationsResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListPresentationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPresentationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPresentationsResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties

	l._rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPresentationsResponse) String() string {
	if len(l._rawJSON) > 0 {
		if value, err := core.StringifyJSON(l._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Presentation detail returned in get responses.
type PresentationDetail struct {
	// Unique identifier for the subscription.
	SubscriptionID *string `json:"subscription_id,omitempty" url:"subscription_id,omitempty"`
	// Unique identifier for the presentation.
	PresentationID *string `json:"presentation_id,omitempty" url:"presentation_id,omitempty"`
	// The ISO 8601 UTC Timestamp when the payment is due.
	DueDate *time.Time          `json:"due_date,omitempty" url:"due_date,omitempty"`
	Amount  *SubscriptionAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Unique identifier of the merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"merchant_presentation_reference,omitempty"`
	// Pre-debit notification status.
	// - CREATED: Pine Labs received the pre-debit notification request.
	// - INITIATED: Pre-debit notification request sent to the Bank.
	// - NOTIFIED: Notification delivered successfully.
	// - FAILED: Notification delivery attempt unsuccessful.
	// - CANCELLED: Notification stopped before completion.
	// - PAUSED: Notification temporarily halted.
	// - PDN_FAILED: Pre-debit notification failed after all retry attempts.
	PdnStatus *PresentationDetailPdnStatus `json:"pdn_status,omitempty" url:"pdn_status,omitempty"`
	// Presentation status.
	// - CREATED: Customer Debit request received.
	// - PENDING: Debit request sent to Bank, awaiting response.
	// - COMPLETED: Debit successfully received.
	// - FAILED: Debit request unsuccessful.
	// - CANCELLED: Cancel Subscription request received.
	// - PAUSED: Pause subscription request received.
	// - PARTIALLY_REFUNDED: Partial refund successful.
	// - REFUNDED: Full refund successful.
	// - INITIATED: Debit request initiated.
	Status *PresentationDetailStatus `json:"status,omitempty" url:"status,omitempty"`
	// The number of times the requests to execute mandates at banks have failed.
	FailureCount *int `json:"failure_count,omitempty" url:"failure_count,omitempty"`
	// Unique identifier of the order created for this presentation.
	OrderID *string `json:"order_id,omitempty" url:"order_id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PresentationDetail) GetSubscriptionID() *string {
	if p == nil {
		return nil
	}
	return p.SubscriptionID
}

func (p *PresentationDetail) GetPresentationID() *string {
	if p == nil {
		return nil
	}
	return p.PresentationID
}

func (p *PresentationDetail) GetDueDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.DueDate
}

func (p *PresentationDetail) GetAmount() *SubscriptionAmount {
	if p == nil {
		return nil
	}
	return p.Amount
}

func (p *PresentationDetail) GetMerchantPresentationReference() *string {
	if p == nil {
		return nil
	}
	return p.MerchantPresentationReference
}

func (p *PresentationDetail) GetPdnStatus() *PresentationDetailPdnStatus {
	if p == nil {
		return nil
	}
	return p.PdnStatus
}

func (p *PresentationDetail) GetStatus() *PresentationDetailStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PresentationDetail) GetFailureCount() *int {
	if p == nil {
		return nil
	}
	return p.FailureCount
}

func (p *PresentationDetail) GetOrderID() *string {
	if p == nil {
		return nil
	}
	return p.OrderID
}

func (p *PresentationDetail) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PresentationDetail) UnmarshalJSON(data []byte) error {
	type embed PresentationDetail
	var unmarshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PresentationDetail(unmarshaler.embed)
	p.DueDate = unmarshaler.DueDate.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PresentationDetail) MarshalJSON() ([]byte, error) {
	type embed PresentationDetail
	var marshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed:   embed(*p),
		DueDate: core.NewOptionalDateTime(p.DueDate),
	}
	return json.Marshal(marshaler)
}

func (p *PresentationDetail) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Pre-debit notification status.
// - CREATED: Pine Labs received the pre-debit notification request.
// - INITIATED: Pre-debit notification request sent to the Bank.
// - NOTIFIED: Notification delivered successfully.
// - FAILED: Notification delivery attempt unsuccessful.
// - CANCELLED: Notification stopped before completion.
// - PAUSED: Notification temporarily halted.
// - PDN_FAILED: Pre-debit notification failed after all retry attempts.
type PresentationDetailPdnStatus string

const (
	PresentationDetailPdnStatusCreated   PresentationDetailPdnStatus = "CREATED"
	PresentationDetailPdnStatusInitiated PresentationDetailPdnStatus = "INITIATED"
	PresentationDetailPdnStatusNotified  PresentationDetailPdnStatus = "NOTIFIED"
	PresentationDetailPdnStatusFailed    PresentationDetailPdnStatus = "FAILED"
	PresentationDetailPdnStatusCancelled PresentationDetailPdnStatus = "CANCELLED"
	PresentationDetailPdnStatusPaused    PresentationDetailPdnStatus = "PAUSED"
	PresentationDetailPdnStatusPdnFailed PresentationDetailPdnStatus = "PDN_FAILED"
)

func NewPresentationDetailPdnStatusFromString(s string) (PresentationDetailPdnStatus, error) {
	switch s {
	case "CREATED":
		return PresentationDetailPdnStatusCreated, nil
	case "INITIATED":
		return PresentationDetailPdnStatusInitiated, nil
	case "NOTIFIED":
		return PresentationDetailPdnStatusNotified, nil
	case "FAILED":
		return PresentationDetailPdnStatusFailed, nil
	case "CANCELLED":
		return PresentationDetailPdnStatusCancelled, nil
	case "PAUSED":
		return PresentationDetailPdnStatusPaused, nil
	case "PDN_FAILED":
		return PresentationDetailPdnStatusPdnFailed, nil
	}
	var t PresentationDetailPdnStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PresentationDetailPdnStatus) Ptr() *PresentationDetailPdnStatus {
	return &p
}

// Presentation status.
// - CREATED: Customer Debit request received.
// - PENDING: Debit request sent to Bank, awaiting response.
// - COMPLETED: Debit successfully received.
// - FAILED: Debit request unsuccessful.
// - CANCELLED: Cancel Subscription request received.
// - PAUSED: Pause subscription request received.
// - PARTIALLY_REFUNDED: Partial refund successful.
// - REFUNDED: Full refund successful.
// - INITIATED: Debit request initiated.
type PresentationDetailStatus string

const (
	PresentationDetailStatusCreated           PresentationDetailStatus = "CREATED"
	PresentationDetailStatusPending           PresentationDetailStatus = "PENDING"
	PresentationDetailStatusCompleted         PresentationDetailStatus = "COMPLETED"
	PresentationDetailStatusFailed            PresentationDetailStatus = "FAILED"
	PresentationDetailStatusCancelled         PresentationDetailStatus = "CANCELLED"
	PresentationDetailStatusPaused            PresentationDetailStatus = "PAUSED"
	PresentationDetailStatusPartiallyRefunded PresentationDetailStatus = "PARTIALLY_REFUNDED"
	PresentationDetailStatusRefunded          PresentationDetailStatus = "REFUNDED"
	PresentationDetailStatusInitiated         PresentationDetailStatus = "INITIATED"
)

func NewPresentationDetailStatusFromString(s string) (PresentationDetailStatus, error) {
	switch s {
	case "CREATED":
		return PresentationDetailStatusCreated, nil
	case "PENDING":
		return PresentationDetailStatusPending, nil
	case "COMPLETED":
		return PresentationDetailStatusCompleted, nil
	case "FAILED":
		return PresentationDetailStatusFailed, nil
	case "CANCELLED":
		return PresentationDetailStatusCancelled, nil
	case "PAUSED":
		return PresentationDetailStatusPaused, nil
	case "PARTIALLY_REFUNDED":
		return PresentationDetailStatusPartiallyRefunded, nil
	case "REFUNDED":
		return PresentationDetailStatusRefunded, nil
	case "INITIATED":
		return PresentationDetailStatusInitiated, nil
	}
	var t PresentationDetailStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PresentationDetailStatus) Ptr() *PresentationDetailStatus {
	return &p
}

// Response returned after sending a subscription notification.
type SubscriptionNotificationResponse struct {
	// Unique identifier for the subscription.
	SubscriptionID *string `json:"subscription_id,omitempty" url:"subscription_id,omitempty"`
	// The ISO 8601 UTC Timestamp of the date & time at which the payment is due.
	DueDate *time.Time `json:"due_date,omitempty" url:"due_date,omitempty"`
	// Unique identifier for the presentation.
	PresentationID *string             `json:"presentation_id,omitempty" url:"presentation_id,omitempty"`
	Amount         *SubscriptionAmount `json:"amount,omitempty" url:"amount,omitempty"`
	// Unique identifier of the merchant presentation reference.
	MerchantPresentationReference *string `json:"merchant_presentation_reference,omitempty" url:"merchant_presentation_reference,omitempty"`
	// Pre-debit notification status.
	PdnStatus *SubscriptionNotificationResponsePdnStatus `json:"pdn_status,omitempty" url:"pdn_status,omitempty"`
	// Subscription presentation status.
	Status *SubscriptionNotificationResponseStatus `json:"status,omitempty" url:"status,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SubscriptionNotificationResponse) GetSubscriptionID() *string {
	if s == nil {
		return nil
	}
	return s.SubscriptionID
}

func (s *SubscriptionNotificationResponse) GetDueDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.DueDate
}

func (s *SubscriptionNotificationResponse) GetPresentationID() *string {
	if s == nil {
		return nil
	}
	return s.PresentationID
}

func (s *SubscriptionNotificationResponse) GetAmount() *SubscriptionAmount {
	if s == nil {
		return nil
	}
	return s.Amount
}

func (s *SubscriptionNotificationResponse) GetMerchantPresentationReference() *string {
	if s == nil {
		return nil
	}
	return s.MerchantPresentationReference
}

func (s *SubscriptionNotificationResponse) GetPdnStatus() *SubscriptionNotificationResponsePdnStatus {
	if s == nil {
		return nil
	}
	return s.PdnStatus
}

func (s *SubscriptionNotificationResponse) GetStatus() *SubscriptionNotificationResponseStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SubscriptionNotificationResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SubscriptionNotificationResponse) UnmarshalJSON(data []byte) error {
	type embed SubscriptionNotificationResponse
	var unmarshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SubscriptionNotificationResponse(unmarshaler.embed)
	s.DueDate = unmarshaler.DueDate.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscriptionNotificationResponse) MarshalJSON() ([]byte, error) {
	type embed SubscriptionNotificationResponse
	var marshaler = struct {
		embed
		DueDate *core.DateTime `json:"due_date,omitempty"`
	}{
		embed:   embed(*s),
		DueDate: core.NewOptionalDateTime(s.DueDate),
	}
	return json.Marshal(marshaler)
}

func (s *SubscriptionNotificationResponse) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Pre-debit notification status.
type SubscriptionNotificationResponsePdnStatus string

const (
	SubscriptionNotificationResponsePdnStatusCreated   SubscriptionNotificationResponsePdnStatus = "CREATED"
	SubscriptionNotificationResponsePdnStatusInitiated SubscriptionNotificationResponsePdnStatus = "INITIATED"
	SubscriptionNotificationResponsePdnStatusNotified  SubscriptionNotificationResponsePdnStatus = "NOTIFIED"
	SubscriptionNotificationResponsePdnStatusFailed    SubscriptionNotificationResponsePdnStatus = "FAILED"
	SubscriptionNotificationResponsePdnStatusCancelled SubscriptionNotificationResponsePdnStatus = "CANCELLED"
	SubscriptionNotificationResponsePdnStatusPaused    SubscriptionNotificationResponsePdnStatus = "PAUSED"
	SubscriptionNotificationResponsePdnStatusPdnFailed SubscriptionNotificationResponsePdnStatus = "PDN_FAILED"
)

func NewSubscriptionNotificationResponsePdnStatusFromString(s string) (SubscriptionNotificationResponsePdnStatus, error) {
	switch s {
	case "CREATED":
		return SubscriptionNotificationResponsePdnStatusCreated, nil
	case "INITIATED":
		return SubscriptionNotificationResponsePdnStatusInitiated, nil
	case "NOTIFIED":
		return SubscriptionNotificationResponsePdnStatusNotified, nil
	case "FAILED":
		return SubscriptionNotificationResponsePdnStatusFailed, nil
	case "CANCELLED":
		return SubscriptionNotificationResponsePdnStatusCancelled, nil
	case "PAUSED":
		return SubscriptionNotificationResponsePdnStatusPaused, nil
	case "PDN_FAILED":
		return SubscriptionNotificationResponsePdnStatusPdnFailed, nil
	}
	var t SubscriptionNotificationResponsePdnStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SubscriptionNotificationResponsePdnStatus) Ptr() *SubscriptionNotificationResponsePdnStatus {
	return &s
}

// Subscription presentation status.
type SubscriptionNotificationResponseStatus string

const (
	SubscriptionNotificationResponseStatusWaitingForExecution SubscriptionNotificationResponseStatus = "WAITING_FOR_EXECUTION"
	SubscriptionNotificationResponseStatusCreated             SubscriptionNotificationResponseStatus = "CREATED"
	SubscriptionNotificationResponseStatusInitiated           SubscriptionNotificationResponseStatus = "INITIATED"
	SubscriptionNotificationResponseStatusNotified            SubscriptionNotificationResponseStatus = "NOTIFIED"
	SubscriptionNotificationResponseStatusFailed              SubscriptionNotificationResponseStatus = "FAILED"
	SubscriptionNotificationResponseStatusCancelled           SubscriptionNotificationResponseStatus = "CANCELLED"
	SubscriptionNotificationResponseStatusPaused              SubscriptionNotificationResponseStatus = "PAUSED"
	SubscriptionNotificationResponseStatusPdnFailed           SubscriptionNotificationResponseStatus = "PDN_FAILED"
)

func NewSubscriptionNotificationResponseStatusFromString(s string) (SubscriptionNotificationResponseStatus, error) {
	switch s {
	case "WAITING_FOR_EXECUTION":
		return SubscriptionNotificationResponseStatusWaitingForExecution, nil
	case "CREATED":
		return SubscriptionNotificationResponseStatusCreated, nil
	case "INITIATED":
		return SubscriptionNotificationResponseStatusInitiated, nil
	case "NOTIFIED":
		return SubscriptionNotificationResponseStatusNotified, nil
	case "FAILED":
		return SubscriptionNotificationResponseStatusFailed, nil
	case "CANCELLED":
		return SubscriptionNotificationResponseStatusCancelled, nil
	case "PAUSED":
		return SubscriptionNotificationResponseStatusPaused, nil
	case "PDN_FAILED":
		return SubscriptionNotificationResponseStatusPdnFailed, nil
	}
	var t SubscriptionNotificationResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SubscriptionNotificationResponseStatus) Ptr() *SubscriptionNotificationResponseStatus {
	return &s
}
