// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CreatePlanRequest struct {
	// Subscription plan name.
	PlanName string `json:"plan_name" url:"-"`
	// Corresponding description for a plan.
	PlanDescription *string `json:"plan_description,omitempty" url:"-"`
	// Frequency of recurring transactions for this particular plan.
	Frequency          CreatePlanRequestFrequency `json:"frequency" url:"-"`
	Amount             *SubscriptionAmount        `json:"amount,omitempty" url:"-"`
	MaxLimitAmount     *SubscriptionAmount        `json:"max_limit_amount,omitempty" url:"-"`
	InitialDebitAmount *SubscriptionAmount        `json:"initial_debit_amount,omitempty" url:"-"`
	// Duration of the trial period in days.
	TrialPeriodInDays *int `json:"trial_period_in_days,omitempty" url:"-"`
	// The ISO 8601 UTC Timestamp when the subscription plan is active and available for use.
	StartDate *time.Time `json:"start_date,omitempty" url:"-"`
	// The ISO 8601 UTC Timestamp when the subscription plan expires.
	EndDate time.Time `json:"end_date" url:"-"`
	// Key-value pairs for additional information. Max 10 pairs, 256 chars each.
	MerchantMetadata map[string]string `json:"merchant_metadata,omitempty" url:"-"`
	// **Idempotency Key.** Unique identifier of the merchant plan reference. Duplicate requests with the same `merchant_plan_reference` will return the existing plan instead of creating a new one.
	MerchantPlanReference string `json:"merchant_plan_reference" url:"-"`
	// Indicates whether auto-debit is enabled for one-time payments under the subscription plan.
	AutoDebitOt *string `json:"auto_debit_ot,omitempty" url:"-"`
}

func (c *CreatePlanRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePlanRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePlanRequest(body)
	return nil
}

func (c *CreatePlanRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePlanRequest
	var marshaler = struct {
		embed
		StartDate *core.DateTime `json:"start_date,omitempty"`
		EndDate   *core.DateTime `json:"end_date"`
	}{
		embed:     embed(*c),
		StartDate: core.NewOptionalDateTime(c.StartDate),
		EndDate:   core.NewDateTime(c.EndDate),
	}
	return json.Marshal(marshaler)
}

type DeletePlanRequest struct {
}

type GetPlanByIDRequest struct {
}

type GetPlanByMerchantReferenceRequest struct {
}

type ListPlansRequest struct {
	// Filter by plan ID.
	PlanID *string `json:"-" url:"plan_id,omitempty"`
	// Filter plans with start date after this value (ISO 8601 UTC).
	StartDate *time.Time `json:"-" url:"start_date,omitempty"`
	// Filter plans with end date before this value (ISO 8601 UTC).
	EndDate *time.Time `json:"-" url:"end_date,omitempty"`
	// Filter by amount value.
	Amount *int `json:"-" url:"amount,omitempty"`
	// Amount comparison operator.
	AmountRange *ListPlansRequestAmountRange `json:"-" url:"amount_range,omitempty"`
	// Filter by billing frequency.
	Frequency *string `json:"-" url:"frequency,omitempty"`
	// Number of items per page.
	Size *int `json:"-" url:"size,omitempty"`
	// Page number.
	Page *int `json:"-" url:"page,omitempty"`
	// Sort field and direction.
	Sort *string `json:"-" url:"sort,omitempty"`
}

type UpdatePlanRequest struct {
	// Subscription plan name.
	PlanName *string `json:"plan_name,omitempty" url:"-"`
	// Corresponding description for a plan.
	PlanDescription *string             `json:"plan_description,omitempty" url:"-"`
	Amount          *SubscriptionAmount `json:"amount,omitempty" url:"-"`
	MaxLimitAmount  *SubscriptionAmount `json:"max_limit_amount,omitempty" url:"-"`
	// Duration of the trial period in days.
	TrialPeriodInDays *int `json:"trial_period_in_days,omitempty" url:"-"`
	// The ISO 8601 UTC Timestamp when the subscription plan expires.
	EndDate *time.Time `json:"end_date,omitempty" url:"-"`
	// Key-value pairs for additional information. Max 10 pairs, 256 chars each.
	MerchantMetadata map[string]string `json:"merchant_metadata,omitempty" url:"-"`
}

func (u *UpdatePlanRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePlanRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdatePlanRequest(body)
	return nil
}

func (u *UpdatePlanRequest) MarshalJSON() ([]byte, error) {
	type embed UpdatePlanRequest
	var marshaler = struct {
		embed
		EndDate *core.DateTime `json:"end_date,omitempty"`
	}{
		embed:   embed(*u),
		EndDate: core.NewOptionalDateTime(u.EndDate),
	}
	return json.Marshal(marshaler)
}

// Response returned when listing all plans.
type ListPlansResponse struct {
	Links *PaginationLinks `json:"links,omitempty" url:"links,omitempty"`
	Page  *PageInfo        `json:"page,omitempty" url:"page,omitempty"`
	// List of plan records.
	Plans []*PlanResponse `json:"plans,omitempty" url:"plans,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (l *ListPlansResponse) GetLinks() *PaginationLinks {
	if l == nil {
		return nil
	}
	return l.Links
}

func (l *ListPlansResponse) GetPage() *PageInfo {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListPlansResponse) GetPlans() []*PlanResponse {
	if l == nil {
		return nil
	}
	return l.Plans
}

func (l *ListPlansResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListPlansResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPlansResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPlansResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties

	l._rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPlansResponse) String() string {
	if len(l._rawJSON) > 0 {
		if value, err := core.StringifyJSON(l._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Frequency of recurring transactions for this particular plan.
type CreatePlanRequestFrequency string

const (
	CreatePlanRequestFrequencyDay           CreatePlanRequestFrequency = "Day"
	CreatePlanRequestFrequencyWeek          CreatePlanRequestFrequency = "Week"
	CreatePlanRequestFrequencyMonth         CreatePlanRequestFrequency = "Month"
	CreatePlanRequestFrequencyYear          CreatePlanRequestFrequency = "Year"
	CreatePlanRequestFrequencyBiMonthly     CreatePlanRequestFrequency = "Bi-Monthly"
	CreatePlanRequestFrequencyQuarterly     CreatePlanRequestFrequency = "Quarterly"
	CreatePlanRequestFrequencyHalfYearly    CreatePlanRequestFrequency = "Half-Yearly"
	CreatePlanRequestFrequencyAs            CreatePlanRequestFrequency = "AS"
	CreatePlanRequestFrequencyOt            CreatePlanRequestFrequency = "OT"
	CreatePlanRequestFrequencyNotApplicable CreatePlanRequestFrequency = "Not Applicable"
)

func NewCreatePlanRequestFrequencyFromString(s string) (CreatePlanRequestFrequency, error) {
	switch s {
	case "Day":
		return CreatePlanRequestFrequencyDay, nil
	case "Week":
		return CreatePlanRequestFrequencyWeek, nil
	case "Month":
		return CreatePlanRequestFrequencyMonth, nil
	case "Year":
		return CreatePlanRequestFrequencyYear, nil
	case "Bi-Monthly":
		return CreatePlanRequestFrequencyBiMonthly, nil
	case "Quarterly":
		return CreatePlanRequestFrequencyQuarterly, nil
	case "Half-Yearly":
		return CreatePlanRequestFrequencyHalfYearly, nil
	case "AS":
		return CreatePlanRequestFrequencyAs, nil
	case "OT":
		return CreatePlanRequestFrequencyOt, nil
	case "Not Applicable":
		return CreatePlanRequestFrequencyNotApplicable, nil
	}
	var t CreatePlanRequestFrequency
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePlanRequestFrequency) Ptr() *CreatePlanRequestFrequency {
	return &c
}

type ListPlansRequestAmountRange string

const (
	ListPlansRequestAmountRangeIsMore  ListPlansRequestAmountRange = "isMore"
	ListPlansRequestAmountRangeIsLess  ListPlansRequestAmountRange = "isLess"
	ListPlansRequestAmountRangeIsEqual ListPlansRequestAmountRange = "is Equal"
)

func NewListPlansRequestAmountRangeFromString(s string) (ListPlansRequestAmountRange, error) {
	switch s {
	case "isMore":
		return ListPlansRequestAmountRangeIsMore, nil
	case "isLess":
		return ListPlansRequestAmountRangeIsLess, nil
	case "is Equal":
		return ListPlansRequestAmountRangeIsEqual, nil
	}
	var t ListPlansRequestAmountRange
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListPlansRequestAmountRange) Ptr() *ListPlansRequestAmountRange {
	return &l
}
