// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type DeleteCustomerTokenRequest struct {
	// Unique reference for this delete operation.
	MerchantUniqueReference string            `json:"merchant_unique_reference" url:"-"`
	MerchantMetadata        *MerchantMetadata `json:"merchant_metadata,omitempty" url:"-"`
}

type DeleteTokenByTokenIDRequest struct {
}

type GenerateCardTokenRequest struct {
	// Unique identifier of the customer in the Pine Labs Online database.
	CustomerID string `json:"customer_id" url:"-"`
	// **Idempotency Key.** Unique token reference assigned by the merchant. Duplicate requests with the same `merchant_token_reference` will return the existing token instead of creating a new one.
	MerchantTokenReference string `json:"merchant_token_reference" url:"-"`
	// Payment method for which the token is being generated. Currently only CARD is supported.
	PaymentMethod    GenerateCardTokenRequestPaymentMethod `json:"payment_method" url:"-"`
	PaymentOption    *TokenPaymentOption                   `json:"payment_option,omitempty" url:"-"`
	Payment          *TokenPayment                         `json:"payment,omitempty" url:"-"`
	MerchantMetadata *MerchantMetadata                     `json:"merchant_metadata,omitempty" url:"-"`
}

type GenerateCryptogramRequest struct {
	// Unique reference for this cryptogram generation request.
	MerchantUniqueReference string `json:"merchant_unique_reference" url:"-"`
	// Service provider token identifier.
	ServiceProviderTokenID string `json:"service_provider_token_id" url:"-"`
}

type GetCustomerTokenByTokenIDRequest struct {
}

type GetCustomerTokensByCustomerIDRequest struct {
}

type GetServiceProviderTokenRequest struct {
}

// Response object after generating a card token.
type CardTokenResponse struct {
	// Unique token ID generated by Pine Labs Online.
	TokenID *string `json:"token_id,omitempty" url:"token_id,omitempty"`
	// Unique identifier of the customer associated with the token.
	CustomerID *string `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	// Merchant's token reference.
	MerchantTokenReference *string      `json:"merchant_token_reference,omitempty" url:"merchant_token_reference,omitempty"`
	Status                 *TokenStatus `json:"status,omitempty" url:"status,omitempty"`
	// ISO 8601 UTC timestamp when the token was created.
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// ISO 8601 UTC timestamp when the token was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CardTokenResponse) GetTokenID() *string {
	if c == nil {
		return nil
	}
	return c.TokenID
}

func (c *CardTokenResponse) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CardTokenResponse) GetMerchantTokenReference() *string {
	if c == nil {
		return nil
	}
	return c.MerchantTokenReference
}

func (c *CardTokenResponse) GetStatus() *TokenStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CardTokenResponse) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CardTokenResponse) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CardTokenResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CardTokenResponse) UnmarshalJSON(data []byte) error {
	type embed CardTokenResponse
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CardTokenResponse(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	c.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CardTokenResponse) MarshalJSON() ([]byte, error) {
	type embed CardTokenResponse
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewOptionalDateTime(c.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *CardTokenResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Response object containing the generated cryptogram data.
type CryptogramResponse struct {
	// Token ID used for the cryptogram generation.
	TokenID *string `json:"token_id,omitempty" url:"token_id,omitempty"`
	// Merchant's token reference.
	MerchantTokenReference *string `json:"merchant_token_reference,omitempty" url:"merchant_token_reference,omitempty"`
	// Service provider token identifier.
	ServiceProviderTokenID *string                 `json:"service_provider_token_id,omitempty" url:"service_provider_token_id,omitempty"`
	TokenData              *TokenTransactionalData `json:"token_data,omitempty" url:"token_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CryptogramResponse) GetTokenID() *string {
	if c == nil {
		return nil
	}
	return c.TokenID
}

func (c *CryptogramResponse) GetMerchantTokenReference() *string {
	if c == nil {
		return nil
	}
	return c.MerchantTokenReference
}

func (c *CryptogramResponse) GetServiceProviderTokenID() *string {
	if c == nil {
		return nil
	}
	return c.ServiceProviderTokenID
}

func (c *CryptogramResponse) GetTokenData() *TokenTransactionalData {
	if c == nil {
		return nil
	}
	return c.TokenData
}

func (c *CryptogramResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CryptogramResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptogramResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptogramResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptogramResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Individual token detail linked to a customer.
type CustomerTokenDetail struct {
	// Unique token ID generated by Pine Labs Online.
	TokenID *string `json:"token_id,omitempty" url:"token_id,omitempty"`
	// Merchant's token reference.
	MerchantTokenReference *string `json:"merchant_token_reference,omitempty" url:"merchant_token_reference,omitempty"`
	// Unique identifier of the customer.
	CustomerID *string      `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	Status     *TokenStatus `json:"status,omitempty" url:"status,omitempty"`
	// Payment method associated with the token.
	PaymentMethod *CustomerTokenDetailPaymentMethod `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	// ISO 8601 UTC timestamp when the token expires.
	ExpiredAt *time.Time `json:"expired_at,omitempty" url:"expired_at,omitempty"`
	// ISO 8601 UTC timestamp when the token was created.
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// ISO 8601 UTC timestamp when the token was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// Reason for the current token status.
	StatusReason     *string           `json:"status_reason,omitempty" url:"status_reason,omitempty"`
	MerchantMetadata *MerchantMetadata `json:"merchant_metadata,omitempty" url:"merchant_metadata,omitempty"`
	CardData         *TokenCardData    `json:"card_data,omitempty" url:"card_data,omitempty"`
	// Indicates whether the token is compliant with regulatory requirements.
	IsCompliant *bool `json:"is_compliant,omitempty" url:"is_compliant,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CustomerTokenDetail) GetTokenID() *string {
	if c == nil {
		return nil
	}
	return c.TokenID
}

func (c *CustomerTokenDetail) GetMerchantTokenReference() *string {
	if c == nil {
		return nil
	}
	return c.MerchantTokenReference
}

func (c *CustomerTokenDetail) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CustomerTokenDetail) GetStatus() *TokenStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CustomerTokenDetail) GetPaymentMethod() *CustomerTokenDetailPaymentMethod {
	if c == nil {
		return nil
	}
	return c.PaymentMethod
}

func (c *CustomerTokenDetail) GetExpiredAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpiredAt
}

func (c *CustomerTokenDetail) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CustomerTokenDetail) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CustomerTokenDetail) GetStatusReason() *string {
	if c == nil {
		return nil
	}
	return c.StatusReason
}

func (c *CustomerTokenDetail) GetMerchantMetadata() *MerchantMetadata {
	if c == nil {
		return nil
	}
	return c.MerchantMetadata
}

func (c *CustomerTokenDetail) GetCardData() *TokenCardData {
	if c == nil {
		return nil
	}
	return c.CardData
}

func (c *CustomerTokenDetail) GetIsCompliant() *bool {
	if c == nil {
		return nil
	}
	return c.IsCompliant
}

func (c *CustomerTokenDetail) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerTokenDetail) UnmarshalJSON(data []byte) error {
	type embed CustomerTokenDetail
	var unmarshaler = struct {
		embed
		ExpiredAt *core.DateTime `json:"expired_at,omitempty"`
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerTokenDetail(unmarshaler.embed)
	c.ExpiredAt = unmarshaler.ExpiredAt.TimePtr()
	c.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	c.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerTokenDetail) MarshalJSON() ([]byte, error) {
	type embed CustomerTokenDetail
	var marshaler = struct {
		embed
		ExpiredAt *core.DateTime `json:"expired_at,omitempty"`
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*c),
		ExpiredAt: core.NewOptionalDateTime(c.ExpiredAt),
		CreatedAt: core.NewOptionalDateTime(c.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *CustomerTokenDetail) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Payment method associated with the token.
type CustomerTokenDetailPaymentMethod string

const (
	CustomerTokenDetailPaymentMethodCard   CustomerTokenDetailPaymentMethod = "CARD"
	CustomerTokenDetailPaymentMethodUpi    CustomerTokenDetailPaymentMethod = "UPI"
	CustomerTokenDetailPaymentMethodPoints CustomerTokenDetailPaymentMethod = "POINTS"
)

func NewCustomerTokenDetailPaymentMethodFromString(s string) (CustomerTokenDetailPaymentMethod, error) {
	switch s {
	case "CARD":
		return CustomerTokenDetailPaymentMethodCard, nil
	case "UPI":
		return CustomerTokenDetailPaymentMethodUpi, nil
	case "POINTS":
		return CustomerTokenDetailPaymentMethodPoints, nil
	}
	var t CustomerTokenDetailPaymentMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomerTokenDetailPaymentMethod) Ptr() *CustomerTokenDetailPaymentMethod {
	return &c
}

// Response object containing all tokens linked to a customer.
type CustomerTokensResponse struct {
	// Unique identifier of the customer.
	CustomerID *string `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	// Total number of tokens linked to the customer.
	TotalTokens *int `json:"total_tokens,omitempty" url:"total_tokens,omitempty"`
	// List of tokens associated with the customer.
	Tokens []*CustomerTokenDetail `json:"tokens,omitempty" url:"tokens,omitempty"`
	// ISO 8601 UTC timestamp when the customer record was created.
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// ISO 8601 UTC timestamp when the customer record was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CustomerTokensResponse) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CustomerTokensResponse) GetTotalTokens() *int {
	if c == nil {
		return nil
	}
	return c.TotalTokens
}

func (c *CustomerTokensResponse) GetTokens() []*CustomerTokenDetail {
	if c == nil {
		return nil
	}
	return c.Tokens
}

func (c *CustomerTokensResponse) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CustomerTokensResponse) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CustomerTokensResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerTokensResponse) UnmarshalJSON(data []byte) error {
	type embed CustomerTokensResponse
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerTokensResponse(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	c.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerTokensResponse) MarshalJSON() ([]byte, error) {
	type embed CustomerTokensResponse
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewOptionalDateTime(c.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *CustomerTokensResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Response after successfully deleting a customer token.
type DeleteCustomerTokenResponse struct {
	// Token ID that was deleted.
	TokenID *string `json:"token_id,omitempty" url:"token_id,omitempty"`
	// Unique identifier of the customer.
	CustomerID *string `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	// Status of the token after deletion.
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Unique reference for this delete operation.
	MerchantUniqueReference *string `json:"merchant_unique_reference,omitempty" url:"merchant_unique_reference,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (d *DeleteCustomerTokenResponse) GetTokenID() *string {
	if d == nil {
		return nil
	}
	return d.TokenID
}

func (d *DeleteCustomerTokenResponse) GetCustomerID() *string {
	if d == nil {
		return nil
	}
	return d.CustomerID
}

func (d *DeleteCustomerTokenResponse) GetStatus() *string {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeleteCustomerTokenResponse) GetMerchantUniqueReference() *string {
	if d == nil {
		return nil
	}
	return d.MerchantUniqueReference
}

func (d *DeleteCustomerTokenResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteCustomerTokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteCustomerTokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteCustomerTokenResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties

	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteCustomerTokenResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Response after deleting a token by its token ID.
type DeleteTokenByTokenIDResponse struct {
	// Token ID that was deleted.
	TokenID *string `json:"token_id,omitempty" url:"token_id,omitempty"`
	// Token status after deletion.
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (d *DeleteTokenByTokenIDResponse) GetTokenID() *string {
	if d == nil {
		return nil
	}
	return d.TokenID
}

func (d *DeleteTokenByTokenIDResponse) GetStatus() *string {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeleteTokenByTokenIDResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteTokenByTokenIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteTokenByTokenIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteTokenByTokenIDResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties

	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteTokenByTokenIDResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Response object containing service provider token information.
type ServiceProviderTokenResponse struct {
	// Unique token ID generated by Pine Labs Online.
	TokenID *string `json:"token_id,omitempty" url:"token_id,omitempty"`
	// Unique identifier of the customer.
	CustomerID *string `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	// Merchant's token reference.
	MerchantTokenReference *string      `json:"merchant_token_reference,omitempty" url:"merchant_token_reference,omitempty"`
	Status                 *TokenStatus `json:"status,omitempty" url:"status,omitempty"`
	// Payment method associated with the token.
	PaymentMethod *ServiceProviderTokenResponsePaymentMethod `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	CardData      *TokenCardData                             `json:"card_data,omitempty" url:"card_data,omitempty"`
	// Service provider token identifier.
	ServiceProviderTokenID *string `json:"service_provider_token_id,omitempty" url:"service_provider_token_id,omitempty"`
	// ISO 8601 UTC timestamp when the token was created.
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// ISO 8601 UTC timestamp when the token was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *ServiceProviderTokenResponse) GetTokenID() *string {
	if s == nil {
		return nil
	}
	return s.TokenID
}

func (s *ServiceProviderTokenResponse) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}

func (s *ServiceProviderTokenResponse) GetMerchantTokenReference() *string {
	if s == nil {
		return nil
	}
	return s.MerchantTokenReference
}

func (s *ServiceProviderTokenResponse) GetStatus() *TokenStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *ServiceProviderTokenResponse) GetPaymentMethod() *ServiceProviderTokenResponsePaymentMethod {
	if s == nil {
		return nil
	}
	return s.PaymentMethod
}

func (s *ServiceProviderTokenResponse) GetCardData() *TokenCardData {
	if s == nil {
		return nil
	}
	return s.CardData
}

func (s *ServiceProviderTokenResponse) GetServiceProviderTokenID() *string {
	if s == nil {
		return nil
	}
	return s.ServiceProviderTokenID
}

func (s *ServiceProviderTokenResponse) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *ServiceProviderTokenResponse) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *ServiceProviderTokenResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ServiceProviderTokenResponse) UnmarshalJSON(data []byte) error {
	type embed ServiceProviderTokenResponse
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = ServiceProviderTokenResponse(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	s.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *ServiceProviderTokenResponse) MarshalJSON() ([]byte, error) {
	type embed ServiceProviderTokenResponse
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at,omitempty"`
		UpdatedAt *core.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*s),
		CreatedAt: core.NewOptionalDateTime(s.CreatedAt),
		UpdatedAt: core.NewOptionalDateTime(s.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *ServiceProviderTokenResponse) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Payment method associated with the token.
type ServiceProviderTokenResponsePaymentMethod string

const (
	ServiceProviderTokenResponsePaymentMethodCard ServiceProviderTokenResponsePaymentMethod = "CARD"
)

func NewServiceProviderTokenResponsePaymentMethodFromString(s string) (ServiceProviderTokenResponsePaymentMethod, error) {
	switch s {
	case "CARD":
		return ServiceProviderTokenResponsePaymentMethodCard, nil
	}
	var t ServiceProviderTokenResponsePaymentMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ServiceProviderTokenResponsePaymentMethod) Ptr() *ServiceProviderTokenResponsePaymentMethod {
	return &s
}

// Response containing a list of service provider tokens for a customer.
type ServiceProviderTokensListResponse struct {
	// Unique identifier of the customer.
	CustomerID *string `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	// List of service provider tokens.
	Tokens []*ServiceProviderTokenResponse `json:"tokens,omitempty" url:"tokens,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *ServiceProviderTokensListResponse) GetCustomerID() *string {
	if s == nil {
		return nil
	}
	return s.CustomerID
}

func (s *ServiceProviderTokensListResponse) GetTokens() []*ServiceProviderTokenResponse {
	if s == nil {
		return nil
	}
	return s.Tokens
}

func (s *ServiceProviderTokensListResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ServiceProviderTokensListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ServiceProviderTokensListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ServiceProviderTokensListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *ServiceProviderTokensListResponse) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Card data associated with a token.
type TokenCardData struct {
	// Last 4 digits of the card number.
	Last4Digit *string `json:"last4_digit,omitempty" url:"last4_digit,omitempty"`
	// Type of card.
	CardType *TokenCardDataCardType `json:"card_type,omitempty" url:"card_type,omitempty"`
	// Card network name.
	NetworkName *string `json:"network_name,omitempty" url:"network_name,omitempty"`
	// Card issuer name.
	IssuerName *string `json:"issuer_name,omitempty" url:"issuer_name,omitempty"`
	// Category of the card.
	CardCategory *string `json:"card_category,omitempty" url:"card_category,omitempty"`
	// Country code of the card issuer.
	CountryCode *string `json:"country_code,omitempty" url:"country_code,omitempty"`
	// Whether the card is an international card.
	International *bool `json:"international,omitempty" url:"international,omitempty"`
	// Whether the card is eligible for EMI.
	Emi *bool `json:"emi,omitempty" url:"emi,omitempty"`
	// Whether CVV is required for transactions with this token.
	CvvRequired *bool `json:"cvv_required,omitempty" url:"cvv_required,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TokenCardData) GetLast4Digit() *string {
	if t == nil {
		return nil
	}
	return t.Last4Digit
}

func (t *TokenCardData) GetCardType() *TokenCardDataCardType {
	if t == nil {
		return nil
	}
	return t.CardType
}

func (t *TokenCardData) GetNetworkName() *string {
	if t == nil {
		return nil
	}
	return t.NetworkName
}

func (t *TokenCardData) GetIssuerName() *string {
	if t == nil {
		return nil
	}
	return t.IssuerName
}

func (t *TokenCardData) GetCardCategory() *string {
	if t == nil {
		return nil
	}
	return t.CardCategory
}

func (t *TokenCardData) GetCountryCode() *string {
	if t == nil {
		return nil
	}
	return t.CountryCode
}

func (t *TokenCardData) GetInternational() *bool {
	if t == nil {
		return nil
	}
	return t.International
}

func (t *TokenCardData) GetEmi() *bool {
	if t == nil {
		return nil
	}
	return t.Emi
}

func (t *TokenCardData) GetCvvRequired() *bool {
	if t == nil {
		return nil
	}
	return t.CvvRequired
}

func (t *TokenCardData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenCardData) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenCardData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenCardData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenCardData) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Type of card.
type TokenCardDataCardType string

const (
	TokenCardDataCardTypeCredit TokenCardDataCardType = "CREDIT"
	TokenCardDataCardTypeDebit  TokenCardDataCardType = "DEBIT"
)

func NewTokenCardDataCardTypeFromString(s string) (TokenCardDataCardType, error) {
	switch s {
	case "CREDIT":
		return TokenCardDataCardTypeCredit, nil
	case "DEBIT":
		return TokenCardDataCardTypeDebit, nil
	}
	var t TokenCardDataCardType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenCardDataCardType) Ptr() *TokenCardDataCardType {
	return &t
}

// An object that contains the payment details.
type TokenPayment struct {
	// An object that contains the acquirer details.
	AcquirerData *TokenPaymentAcquirerData `json:"acquirer_data,omitempty" url:"acquirer_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TokenPayment) GetAcquirerData() *TokenPaymentAcquirerData {
	if t == nil {
		return nil
	}
	return t.AcquirerData
}

func (t *TokenPayment) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenPayment) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenPayment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenPayment(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenPayment) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// An object that contains the acquirer details.
type TokenPaymentAcquirerData struct {
	// Authorization code returned from acquirer against the payment.
	ApprovalCode *string `json:"approval_code,omitempty" url:"approval_code,omitempty"`
	// Unique reference returned from acquirer for the payment.
	AcquirerReference *string `json:"acquirer_reference,omitempty" url:"acquirer_reference,omitempty"`
	// Retrieval reference number returned from acquirer for the payment.
	Rrn *string `json:"rrn,omitempty" url:"rrn,omitempty"`
	// **Mandatory** for rupay transaction. A unique identifier linking the authorization request to the transaction.
	AuthReference *string `json:"auth_reference,omitempty" url:"auth_reference,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TokenPaymentAcquirerData) GetApprovalCode() *string {
	if t == nil {
		return nil
	}
	return t.ApprovalCode
}

func (t *TokenPaymentAcquirerData) GetAcquirerReference() *string {
	if t == nil {
		return nil
	}
	return t.AcquirerReference
}

func (t *TokenPaymentAcquirerData) GetRrn() *string {
	if t == nil {
		return nil
	}
	return t.Rrn
}

func (t *TokenPaymentAcquirerData) GetAuthReference() *string {
	if t == nil {
		return nil
	}
	return t.AuthReference
}

func (t *TokenPaymentAcquirerData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenPaymentAcquirerData) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenPaymentAcquirerData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenPaymentAcquirerData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenPaymentAcquirerData) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// An object that contains the payment option details.
type TokenPaymentOption struct {
	// Encrypted card details.
	EncryptedCardDetails *string `json:"encrypted_card_details,omitempty" url:"encrypted_card_details,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TokenPaymentOption) GetEncryptedCardDetails() *string {
	if t == nil {
		return nil
	}
	return t.EncryptedCardDetails
}

func (t *TokenPaymentOption) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenPaymentOption) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenPaymentOption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenPaymentOption(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenPaymentOption) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Current status of the token.
// - INITIATED: Token creation is initiated.
// - ACTIVE: Token is active and can be used for transactions.
// - SUSPENDED: Token is temporarily suspended.
// - FAILED: Token creation failed.
// - DEACTIVATED: Token has been deactivated.
type TokenStatus string

const (
	TokenStatusInitiated   TokenStatus = "INITIATED"
	TokenStatusActive      TokenStatus = "ACTIVE"
	TokenStatusSuspended   TokenStatus = "SUSPENDED"
	TokenStatusFailed      TokenStatus = "FAILED"
	TokenStatusDeactivated TokenStatus = "DEACTIVATED"
)

func NewTokenStatusFromString(s string) (TokenStatus, error) {
	switch s {
	case "INITIATED":
		return TokenStatusInitiated, nil
	case "ACTIVE":
		return TokenStatusActive, nil
	case "SUSPENDED":
		return TokenStatusSuspended, nil
	case "FAILED":
		return TokenStatusFailed, nil
	case "DEACTIVATED":
		return TokenStatusDeactivated, nil
	}
	var t TokenStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenStatus) Ptr() *TokenStatus {
	return &t
}

// Cryptogram and transactional data for a tokenized transaction.
type TokenTransactionalData struct {
	// The generated cryptogram value for the transaction.
	Cryptogram *string `json:"cryptogram,omitempty" url:"cryptogram,omitempty"`
	// Token reference number.
	TokenReference *string `json:"token_reference,omitempty" url:"token_reference,omitempty"`
	// Payment account reference for the card.
	PaymentAccountReference *string `json:"payment_account_reference,omitempty" url:"payment_account_reference,omitempty"`
	// Token expiry month (2 digits).
	TokenExpiryMonth *string `json:"token_expiry_month,omitempty" url:"token_expiry_month,omitempty"`
	// Token expiry year (4 digits).
	TokenExpiryYear *string `json:"token_expiry_year,omitempty" url:"token_expiry_year,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TokenTransactionalData) GetCryptogram() *string {
	if t == nil {
		return nil
	}
	return t.Cryptogram
}

func (t *TokenTransactionalData) GetTokenReference() *string {
	if t == nil {
		return nil
	}
	return t.TokenReference
}

func (t *TokenTransactionalData) GetPaymentAccountReference() *string {
	if t == nil {
		return nil
	}
	return t.PaymentAccountReference
}

func (t *TokenTransactionalData) GetTokenExpiryMonth() *string {
	if t == nil {
		return nil
	}
	return t.TokenExpiryMonth
}

func (t *TokenTransactionalData) GetTokenExpiryYear() *string {
	if t == nil {
		return nil
	}
	return t.TokenExpiryYear
}

func (t *TokenTransactionalData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenTransactionalData) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenTransactionalData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenTransactionalData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenTransactionalData) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Payment method for which the token is being generated. Currently only CARD is supported.
type GenerateCardTokenRequestPaymentMethod string

const (
	GenerateCardTokenRequestPaymentMethodCard GenerateCardTokenRequestPaymentMethod = "CARD"
)

func NewGenerateCardTokenRequestPaymentMethodFromString(s string) (GenerateCardTokenRequestPaymentMethod, error) {
	switch s {
	case "CARD":
		return GenerateCardTokenRequestPaymentMethodCard, nil
	}
	var t GenerateCardTokenRequestPaymentMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GenerateCardTokenRequestPaymentMethod) Ptr() *GenerateCardTokenRequestPaymentMethod {
	return &g
}

type GetServiceProviderTokenResponse struct {
	ServiceProviderTokensListResponse *ServiceProviderTokensListResponse
	ServiceProviderTokenResponse      *ServiceProviderTokenResponse

	typ string
}

func NewGetServiceProviderTokenResponseFromServiceProviderTokensListResponse(value *ServiceProviderTokensListResponse) *GetServiceProviderTokenResponse {
	return &GetServiceProviderTokenResponse{typ: "ServiceProviderTokensListResponse", ServiceProviderTokensListResponse: value}
}

func NewGetServiceProviderTokenResponseFromServiceProviderTokenResponse(value *ServiceProviderTokenResponse) *GetServiceProviderTokenResponse {
	return &GetServiceProviderTokenResponse{typ: "ServiceProviderTokenResponse", ServiceProviderTokenResponse: value}
}

func (g *GetServiceProviderTokenResponse) GetServiceProviderTokensListResponse() *ServiceProviderTokensListResponse {
	if g == nil {
		return nil
	}
	return g.ServiceProviderTokensListResponse
}

func (g *GetServiceProviderTokenResponse) GetServiceProviderTokenResponse() *ServiceProviderTokenResponse {
	if g == nil {
		return nil
	}
	return g.ServiceProviderTokenResponse
}

func (g *GetServiceProviderTokenResponse) UnmarshalJSON(data []byte) error {
	valueServiceProviderTokensListResponse := new(ServiceProviderTokensListResponse)
	if err := json.Unmarshal(data, &valueServiceProviderTokensListResponse); err == nil {
		g.typ = "ServiceProviderTokensListResponse"
		g.ServiceProviderTokensListResponse = valueServiceProviderTokensListResponse
		return nil
	}
	valueServiceProviderTokenResponse := new(ServiceProviderTokenResponse)
	if err := json.Unmarshal(data, &valueServiceProviderTokenResponse); err == nil {
		g.typ = "ServiceProviderTokenResponse"
		g.ServiceProviderTokenResponse = valueServiceProviderTokenResponse
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetServiceProviderTokenResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "ServiceProviderTokensListResponse" || g.ServiceProviderTokensListResponse != nil {
		return json.Marshal(g.ServiceProviderTokensListResponse)
	}
	if g.typ == "ServiceProviderTokenResponse" || g.ServiceProviderTokenResponse != nil {
		return json.Marshal(g.ServiceProviderTokenResponse)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetServiceProviderTokenResponseVisitor interface {
	VisitServiceProviderTokensListResponse(*ServiceProviderTokensListResponse) error
	VisitServiceProviderTokenResponse(*ServiceProviderTokenResponse) error
}

func (g *GetServiceProviderTokenResponse) Accept(visitor GetServiceProviderTokenResponseVisitor) error {
	if g.typ == "ServiceProviderTokensListResponse" || g.ServiceProviderTokensListResponse != nil {
		return visitor.VisitServiceProviderTokensListResponse(g.ServiceProviderTokensListResponse)
	}
	if g.typ == "ServiceProviderTokenResponse" || g.ServiceProviderTokenResponse != nil {
		return visitor.VisitServiceProviderTokenResponse(g.ServiceProviderTokenResponse)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}
